MESSAGE_TYPE_USER = 1
MESSAGE_TYPE_BOT = 2

MESSAGE_STATE_FINISH = 2

ITEM_TYPE_TEXT = 1
ITEM_TYPE_IMAGE = 2
ITEM_TYPE_VOICE = 3
ITEM_TYPE_FILE = 4
ITEM_TYPE_TOOL_CALL_START = 11
ITEM_TYPE_TOOL_CALL_RESULT = 12

TYPING_STATUS_ACTIVE = 1
TYPING_STATUS_CANCEL = 2

UPLOAD_MEDIA_IMAGE = 1
UPLOAD_MEDIA_FILE = 3
