// Additional stable API errors discovered by the Core handler audit.

package common

import (
	"net/http"
	"regexp"
	"strings"
	"unicode"
)

func init() {
	registerAdditionalError("executor unauthorized", http.StatusUnauthorized, 2001596)
	registerAdditionalError("model config unavailable", http.StatusServiceUnavailable, 2001597)
	registerAdditionalError("invalid task event", http.StatusBadRequest, 2001598)
	registerAdditionalError("persist task event failed", http.StatusServiceUnavailable, 2001599)
	registerAdditionalError("required output missing", http.StatusUnprocessableEntity, 2001600)
	registerAdditionalError("artifact sink requires a database, attempt and slot", http.StatusInternalServerError, 2001993)
	registerAdditionalError("tool config unavailable", http.StatusServiceUnavailable, 2001994)
	registerAdditionalError("advance, retry, and rewind require exactly one target", http.StatusUnprocessableEntity, 2001305)
	registerAdditionalError("algorithm service unavailable", http.StatusBadGateway, 2001306)
	registerAdditionalError("algorithm_id required", http.StatusBadRequest, 2001307)
	registerAdditionalError("aliases must contain word", http.StatusBadRequest, 2001308)
	registerAdditionalError("analysis_id and candidate_id required", http.StatusBadRequest, 2001309)
	registerAdditionalError("another plugin session is active; finish or close it before mentioning a different plugin", http.StatusConflict, 2001310)
	registerAdditionalError("api_key already exists", http.StatusConflict, 2001311)
	registerAdditionalError("api_key is required", http.StatusBadRequest, 2001312)
	registerAdditionalError("api_key is required when using the default base_url", http.StatusBadRequest, 2001313)
	registerAdditionalError("api_key not found", http.StatusNotFound, 2001314)
	registerAdditionalError("at most one plugin mention is allowed per turn", http.StatusBadRequest, 2001315)
	registerAdditionalError("base_url is required", http.StatusBadRequest, 2001316)
	registerAdditionalError("build upstream request failed", http.StatusInternalServerError, 2001317)
	registerAdditionalError("build xlsx template failed", http.StatusInternalServerError, 2001318)
	registerAdditionalError("built-in workflows cannot be modified", http.StatusForbidden, 2001319)
	registerAdditionalError("builtin skill not found", http.StatusNotFound, 2001320)
	registerAdditionalError("cancel running thread failed", http.StatusBadGateway, 2001321)
	registerAdditionalError("candidate not found", http.StatusBadRequest, 2001322)
	registerAdditionalError("candidate_id must include thread_id prefix", http.StatusBadRequest, 2001323)
	registerAdditionalError("candidate_id required", http.StatusBadRequest, 2001324)
	registerAdditionalError("cannot copy directory into its child", http.StatusBadRequest, 2001325)
	registerAdditionalError("cannot move between package root and file path", http.StatusBadRequest, 2001326)
	registerAdditionalError("cannot move directory into its child", http.StatusBadRequest, 2001327)
	registerAdditionalError("cannot write file over directory", http.StatusBadRequest, 2001328)
	registerAdditionalError("cannot write skill root", http.StatusBadRequest, 2001329)
	registerAdditionalError("category cannot be empty", http.StatusBadRequest, 2001330)
	registerAdditionalError("category does not match group", http.StatusBadRequest, 2001331)
	registerAdditionalError("category id required", http.StatusBadRequest, 2001332)
	registerAdditionalError("category is required", http.StatusBadRequest, 2001333)
	registerAdditionalError("category name too long", http.StatusBadRequest, 2001334)
	registerAdditionalError("check existing groups failed", http.StatusInternalServerError, 2001335)
	registerAdditionalError("conflict", http.StatusConflict, 2001336)
	registerAdditionalError("copy requires package-internal paths", http.StatusBadRequest, 2001337)
	registerAdditionalError("create database connection failed", http.StatusInternalServerError, 2001338)
	registerAdditionalError("create failed", http.StatusInternalServerError, 2001339)
	registerAdditionalError("create item failed", http.StatusInternalServerError, 2001340)
	registerAdditionalError("create prompt category failed", http.StatusConflict, 2001341)
	registerAdditionalError("create prompt failed", http.StatusConflict, 2001342)
	registerAdditionalError("create repair run failed", http.StatusInternalServerError, 2001343)
	registerAdditionalError("create upstream thread failed", http.StatusBadGateway, 2001344)
	registerAdditionalError("create word group from conflict failed", http.StatusInternalServerError, 2001345)
	registerAdditionalError("cron_expr and prompt_template are required", http.StatusBadRequest, 2001346)
	registerAdditionalError("custom plugin scripts require the administrator publishing workflow", http.StatusForbidden, 2001347)
	registerAdditionalError("database connection not found", http.StatusNotFound, 2001348)
	registerAdditionalError("dataset_ids required", http.StatusBadRequest, 2001349)
	registerAdditionalError("db unavailable", http.StatusInternalServerError, 2001350)
	registerAdditionalError("decrypt database password failed", http.StatusInternalServerError, 2001351)
	registerAdditionalError("delete database connection failed", http.StatusInternalServerError, 2001352)
	registerAdditionalError("delete item failed", http.StatusInternalServerError, 2001353)
	registerAdditionalError("delete prompt category failed", http.StatusInternalServerError, 2001354)
	registerAdditionalError("delete prompt failed", http.StatusInternalServerError, 2001355)
	registerAdditionalError("delete scan source failed", http.StatusBadGateway, 2001356)
	registerAdditionalError("delete thread failed", http.StatusInternalServerError, 2001357)
	registerAdditionalError("delete upstream thread failed", http.StatusBadGateway, 2001358)
	registerAdditionalError("description or skill_id is required", http.StatusBadRequest, 2001359)
	registerAdditionalError("diff refs must belong to the same skill", http.StatusUnprocessableEntity, 2001360)
	registerAdditionalError("disable tool failed", http.StatusInternalServerError, 2001361)
	registerAdditionalError("dismiss failed", http.StatusInternalServerError, 2001362)
	registerAdditionalError("display_name/content/category required", http.StatusBadRequest, 2001363)
	registerAdditionalError("draft has no generated content to repair", http.StatusBadRequest, 2001364)
	registerAdditionalError("draft_id required", http.StatusBadRequest, 2001365)
	registerAdditionalError("draft_version required", http.StatusBadRequest, 2001366)
	registerAdditionalError("duplicate category in selections", http.StatusBadRequest, 2001367)
	registerAdditionalError("embedding model is not ready", http.StatusUnprocessableEntity, 2001368)
	registerAdditionalError("enable tool failed", http.StatusInternalServerError, 2001369)
	registerAdditionalError("enqueue failed", http.StatusInternalServerError, 2001370)
	registerAdditionalError("estimate context usage failed", http.StatusBadGateway, 2001371)
	registerAdditionalError("eval set item not found", http.StatusNotFound, 2001372)
	registerAdditionalError("eval set not found", http.StatusNotFound, 2001373)
	registerAdditionalError("expected_draft_version required", http.StatusBadRequest, 2001374)
	registerAdditionalError("export context prompt failed", http.StatusBadGateway, 2001375)
	registerAdditionalError("failed to create task", http.StatusInternalServerError, 2001376)
	registerAdditionalError("failed to create task conversation", http.StatusInternalServerError, 2001377)
	registerAdditionalError("failed to marshal ext", http.StatusInternalServerError, 2001378)
	registerAdditionalError("fetch thread flow status failed", http.StatusBadGateway, 2001379)
	registerAdditionalError("file exceeds max size", http.StatusBadRequest, 2001380)
	registerAdditionalError("framework tool unavailable", http.StatusConflict, 2001381)
	registerAdditionalError("generation analysis not found", http.StatusNotFound, 2001382)
	registerAdditionalError("group is not selectable without api_key when using the default base_url", http.StatusBadRequest, 2001383)
	registerAdditionalError("group not found in selected providers", http.StatusNotFound, 2001384)
	registerAdditionalError("import task not found", http.StatusNotFound, 2001385)
	registerAdditionalError("internal token required", http.StatusUnauthorized, 2001386)
	registerAdditionalError("invalid category", http.StatusBadRequest, 2001387)
	registerAdditionalError("invalid cron expression", http.StatusBadRequest, 2001388)
	registerAdditionalError("invalid cron_expr", http.StatusBadRequest, 2001389)
	registerAdditionalError("invalid eval_set_id", http.StatusBadRequest, 2001390)
	registerAdditionalError("invalid import_token", http.StatusBadRequest, 2001391)
	registerAdditionalError("invalid merge item", http.StatusBadRequest, 2001392)
	registerAdditionalError("invalid repair mode", http.StatusBadRequest, 2001393)
	registerAdditionalError("invalid repair target", http.StatusBadRequest, 2001394)
	registerAdditionalError("invalid resource_type", http.StatusBadRequest, 2001395)
	registerAdditionalError("invalid scope", http.StatusBadRequest, 2001396)
	registerAdditionalError("invalid sort", http.StatusBadRequest, 2001397)
	registerAdditionalError("invalid start command", http.StatusBadRequest, 2001398)
	registerAdditionalError("invalid start plan", http.StatusBadRequest, 2001399)
	registerAdditionalError("invalid task_id", http.StatusBadRequest, 2001400)
	registerAdditionalError("invalid transition command", http.StatusBadRequest, 2001401)
	registerAdditionalError("item_id required", http.StatusBadRequest, 2001402)
	registerAdditionalError("list mcp servers failed", http.StatusInternalServerError, 2001403)
	registerAdditionalError("list provider groups failed", http.StatusInternalServerError, 2001404)
	registerAdditionalError("load chat runtime config failed", http.StatusInternalServerError, 2001405)
	registerAdditionalError("load llm config failed", http.StatusInternalServerError, 2001406)
	registerAdditionalError("load local fs chat paths failed", http.StatusInternalServerError, 2001407)
	registerAdditionalError("lock failed", http.StatusInternalServerError, 2001408)
	registerAdditionalError("marshal thread payload failed", http.StatusInternalServerError, 2001409)
	registerAdditionalError("mcp server not found", http.StatusNotFound, 2001410)
	registerAdditionalError("memory review result not found", http.StatusNotFound, 2001411)
	registerAdditionalError("merges is required", http.StatusBadRequest, 2001412)
	registerAdditionalError("metadata field required", http.StatusBadRequest, 2001413)
	registerAdditionalError("missing builtin_skill_uid", http.StatusBadRequest, 2001414)
	registerAdditionalError("missing connection", http.StatusBadRequest, 2001415)
	registerAdditionalError("missing market_item_id", http.StatusBadRequest, 2001416)
	registerAdditionalError("missing review_id", http.StatusBadRequest, 2001417)
	registerAdditionalErrorAlias("missing revision_id", "revision_id required", http.StatusBadRequest, 2001509)
	registerAdditionalErrorAlias("missing task_id", "task_id is required", http.StatusBadRequest, 2001537)
	registerAdditionalError("missing version_id", http.StatusBadRequest, 2001420)
	registerAdditionalError("model not found in selected models", http.StatusNotFound, 2001421)
	registerAdditionalError("move requires skill paths", http.StatusBadRequest, 2001422)
	registerAdditionalError("multimodal embedding model is not ready", http.StatusUnprocessableEntity, 2001423)
	registerAdditionalError("name cannot be empty", http.StatusBadRequest, 2001424)
	registerAdditionalErrorAlias("name is required", "name required", http.StatusBadRequest, 2000860)
	registerAdditionalError("name/category required", http.StatusBadRequest, 2001426)
	registerAdditionalError("no internal skills selected", http.StatusBadRequest, 2001427)
	registerAdditionalError("no slot binding", http.StatusBadRequest, 2001428)
	registerAdditionalError("no valid fields to update", http.StatusBadRequest, 2001429)
	registerAdditionalError("normalize upload text encoding failed", http.StatusBadRequest, 2001430)
	registerAdditionalError("not found", http.StatusNotFound, 2001431)
	registerAdditionalError("operation must be advance, execute, execute_batch, retry, or rewind", http.StatusUnprocessableEntity, 2001432)
	registerAdditionalError("order lookup failed", http.StatusInternalServerError, 2001433)
	registerAdditionalError("order_version conflict; refresh and retry", http.StatusConflict, 2001434)
	registerAdditionalError("overwrite is not supported", http.StatusBadRequest, 2001435)
	registerAdditionalError("parent directory does not exist", http.StatusBadRequest, 2001436)
	registerAdditionalError("patch item failed", http.StatusInternalServerError, 2001437)
	registerAdditionalError("path is a directory", http.StatusBadRequest, 2001438)
	registerAdditionalErrorAlias("path is required", "Path is required", http.StatusBadRequest, 2000209)
	registerAdditionalError("path must include category and skill name", http.StatusBadRequest, 2001440)
	registerAdditionalError("path must start with skills", http.StatusBadRequest, 2001441)
	registerAdditionalError("permanent delete requires permanent=true and confirm=true", http.StatusBadRequest, 2001442)
	registerAdditionalError("persist search_config failed", http.StatusInternalServerError, 2001443)
	registerAdditionalError("personal resource generate failed", http.StatusBadGateway, 2001444)
	registerAdditionalError("plugin draft has no changes from its base revision", http.StatusConflict, 2001445)
	registerAdditionalError("plugin draft not found", http.StatusNotFound, 2001446)
	registerAdditionalError("plugin id already exists for this user", http.StatusConflict, 2001447)
	registerAdditionalError("plugin not found", http.StatusNotFound, 2001448)
	registerAdditionalError("plugin validation failed", http.StatusUnprocessableEntity, 2001449)
	registerAdditionalError("workflow.yaml id required", http.StatusBadRequest, 2001450)
	registerAdditionalError("workflow_id is required", http.StatusUnprocessableEntity, 2001451)
	registerAdditionalErrorAlias("workflow_id required", "workflow_id is required", http.StatusBadRequest, 2001451)
	registerAdditionalError("workflow_mode must be 'auto' or 'dynamic'", http.StatusBadRequest, 2001453)
	registerAdditionalError("polish failed", http.StatusInternalServerError, 2001454)
	registerAdditionalError("post thread action failed", http.StatusBadGateway, 2001455)
	registerAdditionalError("prepare chat attachments failed", http.StatusBadGateway, 2001456)
	registerAdditionalError("preset prompt is read only", http.StatusForbidden, 2001457)
	registerAdditionalError("preview eval set import failed", http.StatusInternalServerError, 2001458)
	registerAdditionalError("project session failed", http.StatusUnprocessableEntity, 2001459)
	registerAdditionalError("prompt category already exists", http.StatusConflict, 2001460)
	registerAdditionalError("prompt category not found", http.StatusNotFound, 2001461)
	registerAdditionalError("prompt polish failed", http.StatusBadGateway, 2001462)
	registerAdditionalError("provider_name and base_url are required", http.StatusBadRequest, 2001463)
	registerAdditionalError("proxy evo request failed", http.StatusBadGateway, 2001464)
	registerAdditionalError("publish failed", http.StatusInternalServerError, 2001465)
	registerAdditionalError("query active session failed", http.StatusInternalServerError, 2001466)
	registerAdditionalError("query artifacts failed", http.StatusInternalServerError, 2001467)
	registerAdditionalError("query conversation artifacts failed", http.StatusInternalServerError, 2001468)
	registerAdditionalError("query conversation failed", http.StatusInternalServerError, 2001469)
	registerAdditionalError("query database connection failed", http.StatusInternalServerError, 2001470)
	registerAdditionalError("query database connections failed", http.StatusInternalServerError, 2001471)
	registerAdditionalError("query disabled tools failed", http.StatusInternalServerError, 2001472)
	registerAdditionalError("query failed", http.StatusInternalServerError, 2001473)
	registerAdditionalError("query group models failed", http.StatusInternalServerError, 2001474)
	registerAdditionalError("query latest session failed", http.StatusInternalServerError, 2001475)
	registerAdditionalError("query local fs chat setting failed", http.StatusInternalServerError, 2001476)
	registerAdditionalError("query memory review result failed", http.StatusInternalServerError, 2001477)
	registerAdditionalError("query memory review results failed", http.StatusInternalServerError, 2001478)
	registerAdditionalError("query order failed", http.StatusInternalServerError, 2001479)
	registerAdditionalError("query prompt categories failed", http.StatusInternalServerError, 2001480)
	registerAdditionalError("query prompt states failed", http.StatusInternalServerError, 2001481)
	registerAdditionalError("query prompt usage failed", http.StatusInternalServerError, 2001482)
	registerAdditionalError("query resource version failed", http.StatusInternalServerError, 2001483)
	registerAdditionalError("query resource versions failed", http.StatusInternalServerError, 2001484)
	registerAdditionalError("query selected providers failed", http.StatusInternalServerError, 2001485)
	registerAdditionalError("query session failed", http.StatusInternalServerError, 2001486)
	registerAdditionalError("query sessions failed", http.StatusInternalServerError, 2001487)
	registerAdditionalError("query skill review summary failed", http.StatusInternalServerError, 2001488)
	registerAdditionalError("query slots failed", http.StatusInternalServerError, 2001489)
	registerAdditionalError("query steps failed", http.StatusInternalServerError, 2001490)
	registerAdditionalError("query subagent artifacts failed", http.StatusInternalServerError, 2001491)
	registerAdditionalError("query task artifacts failed", http.StatusInternalServerError, 2001492)
	registerAdditionalError("query task failed", http.StatusInternalServerError, 2001493)
	registerAdditionalError("query uploaded files failed", http.StatusInternalServerError, 2001494)
	registerAdditionalError("query user preference status failed", http.StatusInternalServerError, 2001495)
	registerAdditionalError("query user ui preferences failed", http.StatusInternalServerError, 2001496)
	registerAdditionalError("query verified provider failed", http.StatusInternalServerError, 2001497)
	registerAdditionalError("query versions failed", http.StatusInternalServerError, 2001498)
	registerAdditionalError("read events failed", http.StatusInternalServerError, 2001499)
	registerAdditionalError("record prompt usage failed", http.StatusInternalServerError, 2001500)
	registerAdditionalError("reload failed", http.StatusInternalServerError, 2001501)
	registerAdditionalError("reorder failed", http.StatusInternalServerError, 2001502)
	registerAdditionalError("repair in progress, please wait", http.StatusConflict, 2001503)
	registerAdditionalError("repair run not found", http.StatusNotFound, 2001504)
	registerAdditionalError("repair stale draft", http.StatusConflict, 2001505)
	registerAdditionalError("reserve transition command failed", http.StatusServiceUnavailable, 2001506)
	registerAdditionalError("resource version not found", http.StatusNotFound, 2001507)
	registerAdditionalError("restore failed", http.StatusInternalServerError, 2001508)
	registerAdditionalError("revision_id required", http.StatusBadRequest, 2001509)
	registerAdditionalError("rollback failed", http.StatusInternalServerError, 2001510)
	registerAdditionalError("run skill review failed", http.StatusInternalServerError, 2001511)
	registerAdditionalError("save failed", http.StatusInternalServerError, 2001512)
	registerAdditionalError("save selected provider failed", http.StatusInternalServerError, 2001513)
	registerAdditionalError("schedule not found", http.StatusNotFound, 2001514)
	registerAdditionalError("schedule_id required", http.StatusBadRequest, 2001515)
	registerAdditionalError("search_config required", http.StatusBadRequest, 2001516)
	registerAdditionalError("select revision failed", http.StatusInternalServerError, 2001517)
	registerAdditionalError("session is dismissed", http.StatusConflict, 2001518)
	registerAdditionalError("session not found", http.StatusNotFound, 2001519)
	registerAdditionalError("session not found or already dismissed", http.StatusNotFound, 2001520)
	registerAdditionalError("session step not found", http.StatusNotFound, 2001521)
	registerAdditionalError("session_id and slot_id required", http.StatusBadRequest, 2001522)
	registerAdditionalError("session_id, slot_id and list_index required", http.StatusBadRequest, 2001523)
	registerAdditionalError("share item is not pending", http.StatusConflict, 2001524)
	registerAdditionalError("skill draft not initialized", http.StatusInternalServerError, 2001525)
	registerAdditionalError("skill generate returned empty content", http.StatusBadGateway, 2001526)
	registerAdditionalError("skill must be in trash before permanent delete", http.StatusBadRequest, 2001527)
	registerAdditionalError("skill organize call failed", http.StatusBadGateway, 2001528)
	registerAdditionalError("skill organize returned unexpected response", http.StatusBadGateway, 2001529)
	registerAdditionalError("slot has no existing items; cannot infer slot", http.StatusBadRequest, 2001530)
	registerAdditionalError("slot revision not found", http.StatusNotFound, 2001531)
	registerAdditionalError("source analysis not found", http.StatusBadRequest, 2001532)
	registerAdditionalError("target revision not found", http.StatusNotFound, 2001533)
	registerAdditionalError("target_fields is required", http.StatusBadRequest, 2001534)
	registerAdditionalError("target_revision_id required", http.StatusBadRequest, 2001535)
	registerAdditionalError("task already in terminal state", http.StatusBadRequest, 2001536)
	registerAdditionalError("task_id is required", http.StatusBadRequest, 2001537)
	registerAdditionalErrorAlias("task_id required", "task_id is required", http.StatusBadRequest, 2001537)
	registerAdditionalError("this provider does not support models", http.StatusBadRequest, 2001539)
	registerAdditionalError("this provider only allows one group per user", http.StatusConflict, 2001540)
	registerAdditionalError("thread_id query is required", http.StatusBadRequest, 2001541)
	registerAdditionalError("tool cannot be disabled", http.StatusBadRequest, 2001542)
	registerAdditionalError("tool not found", http.StatusNotFound, 2001543)
	registerAdditionalError("tool_name required", http.StatusBadRequest, 2001544)
	registerAdditionalError("transition command not found", http.StatusNotFound, 2001545)
	registerAdditionalError("trash requires a skill package root", http.StatusBadRequest, 2001546)
	registerAdditionalError("unsafe path", http.StatusBadRequest, 2001547)
	registerAdditionalError("unsupported file_type", http.StatusBadRequest, 2001548)
	registerAdditionalError("unsupported for personal resource", http.StatusUnprocessableEntity, 2001549)
	registerAdditionalError("update api_key failed", http.StatusInternalServerError, 2001550)
	registerAdditionalError("update caption failed", http.StatusInternalServerError, 2001551)
	registerAdditionalError("update database connection check result failed", http.StatusInternalServerError, 2001552)
	registerAdditionalError("update database connection failed", http.StatusInternalServerError, 2001553)
	registerAdditionalError("update favorite failed", http.StatusInternalServerError, 2001554)
	registerAdditionalError("update local fs chat setting failed", http.StatusInternalServerError, 2001555)
	registerAdditionalError("update prompt failed", http.StatusConflict, 2001556)
	registerAdditionalError("update share failed", http.StatusInternalServerError, 2001557)
	registerAdditionalError("update skill organize reservation failed", http.StatusInternalServerError, 2001558)
	registerAdditionalError("update slot failed", http.StatusInternalServerError, 2001559)
	registerAdditionalError("update user ui preferences failed", http.StatusInternalServerError, 2001560)
	registerAdditionalError("upload belongs to another user", http.StatusForbidden, 2001561)
	registerAdditionalError("upload is not completed", http.StatusBadRequest, 2001562)
	registerAdditionalError("upstream error", http.StatusBadGateway, 2001563)
	registerAdditionalError("upstream request failed", http.StatusBadGateway, 2001564)
	registerAdditionalError("user not found", http.StatusUnauthorized, 2001565)
	registerAdditionalErrorAlias("user_id is required", "user_id required", http.StatusUnauthorized, 2000900)
	registerAdditionalError("user_preference metadata is only supported for user_preference", http.StatusBadRequest, 2001567)
	registerAdditionalError("value must not be empty", http.StatusBadRequest, 2001568)
	registerAdditionalError("verification failed", http.StatusBadGateway, 2001569)
	registerAdditionalError("version conflict", http.StatusConflict, 2001570)
	registerAdditionalError("version not found", http.StatusNotFound, 2001571)
	registerAdditionalError("version required", http.StatusBadRequest, 2001572)
	registerAdditionalError("workflow confirmation stale", http.StatusConflict, 2001573)
	registerAdditionalError("write slot revision failed", http.StatusInternalServerError, 2001574)
	registerAdditionalError("无法查询 skill 维护任务状态", http.StatusServiceUnavailable, 2001575)
	registerAdditionalError("请先配置 llm 和 evo_llm 模型后再创建任务", http.StatusUnprocessableEntity, 2001576)

	// systemdeps / local ffmpeg dependency management
	registerAdditionalError("local runtime root is not configured", http.StatusServiceUnavailable, 2001577)
	registerAdditionalError("load ffmpeg dependency status failed", http.StatusInternalServerError, 2001578)
	registerAdditionalError("ffmpeg dependency settings are only supported in local/desktop runtime", http.StatusForbidden, 2001579)
	registerAdditionalError("source must be custom or bundled", http.StatusBadRequest, 2001580)
	registerAdditionalError("customPath is required when source is custom", http.StatusBadRequest, 2001581)
	registerAdditionalError("bundled ffmpeg install is only supported in local/desktop runtime", http.StatusForbidden, 2001582)
	registerAdditionalError("runtime root is not configured", http.StatusServiceUnavailable, 2001583)
	registerAdditionalError("ffmpeg executable not found", http.StatusBadRequest, 2001584)
	registerAdditionalError("ffprobe was not found next to the selected ffmpeg binary", http.StatusBadRequest, 2001585)
	registerAdditionalError("extract ffmpeg download failed", http.StatusBadRequest, 2001586)
	registerAdditionalError("downloaded ffmpeg archives did not contain ffmpeg and ffprobe binaries", http.StatusBadRequest, 2001587)
	registerAdditionalError("ffmpeg install finished but binaries were not detected", http.StatusInternalServerError, 2001588)
	registerAdditionalError("ffmpeg download failed", http.StatusBadGateway, 2001589)
	registerAdditionalError("write ffmpeg download failed", http.StatusInternalServerError, 2001590)
	registerAdditionalError("unsupported ffmpeg archive format", http.StatusBadRequest, 2001591)
	registerAdditionalErrorPattern("bundled ffmpeg install is not supported on %s/%s", "bundled ffmpeg install is not supported on this platform", http.StatusBadRequest, 2001592)
	registerAdditionalErrorPattern("downloaded %s binary could not run", "downloaded ffmpeg binary could not run", http.StatusInternalServerError, 2001593)
	registerAdditionalError("ffmpeg download checksum mismatch", http.StatusBadGateway, 2001594)
	registerAdditionalError("workflow session has no pinned public revision", http.StatusUnprocessableEntity, 2001595)

	// Workflow and hosted external Agent errors.
	registerAdditionalError("at most one workflow mention is allowed per turn", http.StatusBadRequest, 2002022)
	registerAdditionalError("resolve conversation workflow binding failed", http.StatusInternalServerError, 2002023)
	registerAdditionalError("another workflow session is active; finish or close it before mentioning a different workflow", http.StatusConflict, 2002024)
	registerAdditionalError("invalid agent invocation", http.StatusBadRequest, 2002025)
	registerAdditionalError("agent invocation not found", http.StatusNotFound, 2002026)
	registerAdditionalError("agent invocation conflicts with an existing record", http.StatusConflict, 2002027)
	registerAdditionalError("task is terminal", http.StatusConflict, 2002049)
	registerAdditionalError("chat_executor must be 'lazymind', 'codex', 'cursor', or 'workbuddy'", http.StatusBadRequest, 2002050)
	registerAdditionalError("conversation has an unsupported chat executor", http.StatusConflict, 2002051)
	registerAdditionalError("external chat executors require streaming", http.StatusConflict, 2002052)
	registerAdditionalError("unsupported external chat provider", http.StatusBadRequest, 2002053)
	registerAdditionalError("valid provider and host_id are required", http.StatusBadRequest, 2002054)
	registerAdditionalError("host_id and lease_token are required", http.StatusBadRequest, 2002055)
	registerAdditionalError("host_id, lease_token and event_id are required", http.StatusBadRequest, 2002056)
	registerAdditionalError("unsupported external chat event", http.StatusBadRequest, 2002057)
	registerAdditionalError("external chat lease is no longer owned by this host", http.StatusConflict, 2002058)
	registerAdditionalError("external chat event_id conflicts with an existing event", http.StatusConflict, 2002059)
	registerAdditionalError("external chat store is unavailable", http.StatusServiceUnavailable, 2002060)
	registerAdditionalError("unsupported chat executor", http.StatusBadRequest, 2002061)
	registerAdditionalError("external chat requires an authenticated user", http.StatusUnauthorized, 2002062)
	registerAdditionalErrorPattern("%s Agent host is offline; start `lazymind agent host run` and retry", "External Agent host is offline", http.StatusServiceUnavailable, 2002063)
	registerAdditionalError("create external chat run", http.StatusInternalServerError, 2002064)
	registerAdditionalError("external Agent failed", http.StatusBadGateway, 2002065)
	registerAdditionalError("host_id is too long", http.StatusBadRequest, 2002066)
	registerAdditionalError("event_id is too long", http.StatusBadRequest, 2002067)
	registerAdditionalError("stop external chat failed", http.StatusServiceUnavailable, 2002068)
	registerAdditionalErrorPattern("query %s Agent Host", "Query external Agent Host failed", http.StatusServiceUnavailable, 2002069)
	registerAdditionalErrorPattern("%s is unavailable", "External Agent is unavailable", http.StatusServiceUnavailable, 2002070)
	registerAdditionalError("read external chat events", http.StatusServiceUnavailable, 2002071)
	registerAdditionalError("external chat event payload is too large", http.StatusBadRequest, 2002072)
	registerAdditionalError("external Agent lease is invalid or expired", http.StatusConflict, 2002073)
	registerAdditionalError("external chat idempotency key is too long", http.StatusBadRequest, 2002074)
	registerAdditionalErrorAlias("external chat request_id is too long", "external chat idempotency key is too long", http.StatusBadRequest, 2002074)
	registerAdditionalError("external chat idempotency key conflicts with another request", http.StatusConflict, 2002075)
	registerAdditionalError("query external chat idempotency record failed", http.StatusServiceUnavailable, 2002076)
	registerAdditionalError("algorithm chat stream failed", http.StatusBadGateway, 2002077)
	registerAdditionalError("chat service returned no answer", http.StatusBadGateway, 2002078)
	registerAdditionalError("knowledge backend id is empty", http.StatusInternalServerError, 2002079)
	registerAdditionalError("unaligned page token offset", http.StatusBadRequest, 2002080)
	registerAdditionalError("chunk backend business code failed", http.StatusBadGateway, 2002081)
	registerAdditionalError("chunk backend business status failed", http.StatusBadGateway, 2002082)
	registerAdditionalError("chunk backend business success failed", http.StatusBadGateway, 2002083)
	registerAdditionalError("inline artifact content is missing or exceeds 20 mib", http.StatusBadRequest, 2002084)
	registerAdditionalError("inline artifact content is invalid or exceeds 20 mib", http.StatusBadRequest, 2002085)
	registerAdditionalError("inline artifact filename is invalid", http.StatusBadRequest, 2002086)
	registerAdditionalError("inline artifact size does not match content", http.StatusBadRequest, 2002087)
	registerAdditionalError("inline artifact sha256 does not match content", http.StatusBadRequest, 2002088)
	registerAdditionalError("create workflow artifact directory", http.StatusInternalServerError, 2002089)
	registerAdditionalError("encode managed artifact metadata", http.StatusInternalServerError, 2002090)
	registerAdditionalError("managed artifact path is outside lazymind storage", http.StatusInternalServerError, 2002091)
	registerAdditionalError("read managed artifact", http.StatusInternalServerError, 2002092)
	registerAdditionalError("managed artifact exceeds 20 mib", http.StatusInternalServerError, 2002093)
	registerAdditionalError("managed artifact sha256 does not match content", http.StatusInternalServerError, 2002094)
	registerAdditionalError("create managed artifact", http.StatusInternalServerError, 2002095)
	registerAdditionalError("write managed artifact", http.StatusInternalServerError, 2002096)
	registerAdditionalError("commit managed artifact", http.StatusInternalServerError, 2002097)

}

func registerAdditionalError(message string, status, code int) {
	if _, exists := errorCatalog[message]; exists {
		panic("duplicate Core error catalog message: " + message)
	}
	errorCatalog[message] = NewAppError(status, code, message)
}

func registerAdditionalErrorAlias(alias, message string, status, code int) {
	if _, exists := errorCatalog[alias]; exists {
		panic("duplicate Core error catalog alias: " + alias)
	}
	errorCatalog[alias] = NewAppError(status, code, message)
}

func registerAdditionalErrorPattern(template, message string, status, code int) {
	normalizedTemplate := normalizeErrorKey(template)
	for _, pattern := range errorPatterns {
		if pattern.template == normalizedTemplate {
			panic("duplicate Core error catalog pattern: " + template)
		}
	}
	errorPatterns = append(errorPatterns, errorPattern{
		template: normalizedTemplate,
		matcher:  compileErrorPattern(normalizedTemplate),
		appErr:   NewAppError(status, code, message),
	})
}

func compileErrorPattern(template string) *regexp.Regexp {
	var pattern strings.Builder
	pattern.WriteString("^")
	for index := 0; index < len(template); {
		percent := strings.IndexByte(template[index:], '%')
		if percent < 0 {
			pattern.WriteString(regexp.QuoteMeta(template[index:]))
			break
		}
		percent += index
		pattern.WriteString(regexp.QuoteMeta(template[index:percent]))
		if percent+1 < len(template) && template[percent+1] == '%' {
			pattern.WriteString("%")
			index = percent + 2
			continue
		}
		verb := percent + 1
		for verb < len(template) && !unicode.IsLetter(rune(template[verb])) {
			verb++
		}
		if verb >= len(template) {
			pattern.WriteString("%")
			index = percent + 1
			continue
		}
		pattern.WriteString(".+?")
		index = verb + 1
	}
	pattern.WriteString("$")
	return regexp.MustCompile(pattern.String())
}
