// Stable errors discovered by the Scan Control Plane error-site audit.

package server

import "net/http"

func init() {
	registerError("a data source with this name already exists", "DATA_SOURCE_NAME_ALREADY_EXISTS", "A data source with this name already exists", http.StatusConflict)
	registerError("access checker is not configured", "ACCESS_CHECKER_NOT_CONFIGURED", "Access checker is not configured", http.StatusInternalServerError)
	registerError("access token is empty", "ACCESS_TOKEN_IS_EMPTY", "Access token is empty", http.StatusUnauthorized)
	registerError("action: must be read, write, upload, or delete", "ACTION_MUST_BE_READ_WRITE_UPLOAD_OR_DELETE", "Action: must be read, write, upload, or delete", http.StatusBadRequest)
	registerError("address is required", "ADDRESS_REQUIRED", "Address is required", http.StatusBadRequest)
	registerError("admin service is not configured", "ADMIN_SERVICE_NOT_CONFIGURED", "Admin service is not configured", http.StatusInternalServerError)
	registerError("agent base url is required", "AGENT_BASE_URL_REQUIRED", "Agent base url is required", http.StatusBadRequest)
	registerError("agent base url must include scheme and host", "AGENT_BASE_URL_MUST_INCLUDE_SCHEME_AND_HOST", "Agent base URL must include a scheme and host", http.StatusBadRequest)
	registerError("agent client is not configured", "AGENT_CLIENT_NOT_CONFIGURED", "Agent client is not configured", http.StatusInternalServerError)
	registerError("agent store is not configured", "AGENT_STORE_NOT_CONFIGURED", "Agent store is not configured", http.StatusInternalServerError)
	registerError("agent token is not configured", "AGENT_TOKEN_NOT_CONFIGURED", "Agent token is not configured", http.StatusInternalServerError)
	registerError("agent_id and path are required to build object_key", "AGENT_ID_AND_PATH_ARE_REQUIRED_TO_BUILD_OBJECT_KEY", "Agent_id and path are required to build object_key", http.StatusBadRequest)
	registerError("agent_id and path provider meta are required", "AGENT_ID_AND_PATH_PROVIDER_META_ARE_REQUIRED", "Agent_id and path provider meta are required", http.StatusBadRequest)
	registerError("agent_id is required", "AGENT_ID_REQUIRED", "Agent_id is required", http.StatusBadRequest)
	registerError("agent_id: required", "AGENT_ID_REQUIRED", "Agent_id is required", http.StatusBadRequest)
	registerError("apply runtime schema repair", "APPLY_RUNTIME_SCHEMA_REPAIR", "Failed to apply the runtime schema repair", http.StatusInternalServerError)
	registerErrorPattern("apply scan-control-plane baseline migration %s", "APPLY_SCAN_CONTROL_PLANE_BASELINE_MIGRATION_FAILED", "Failed to apply the scan-control-plane baseline migration", http.StatusInternalServerError)
	registerError("auth connection client is not configured", "AUTH_CONNECTION_CLIENT_NOT_CONFIGURED", "Auth connection client is not configured", http.StatusInternalServerError)
	registerError("auth connection verifier is not configured", "AUTH_CONNECTION_VERIFIER_NOT_CONFIGURED", "Auth connection verifier is not configured", http.StatusInternalServerError)
	registerError("auth service admin verifier is not configured", "AUTH_SERVICE_ADMIN_VERIFIER_NOT_CONFIGURED", "Auth service admin verifier is not configured", http.StatusInternalServerError)
	registerError("auth service base url is required", "AUTH_SERVICE_BASE_URL_REQUIRED", "Auth service base url is required", http.StatusBadRequest)
	registerError("auth service internal token is required", "AUTH_SERVICE_INTERNAL_TOKEN_REQUIRED", "Auth service internal token is required", http.StatusBadRequest)
	registerError("auth service validate failed", "AUTH_SERVICE_VALIDATE_FAILED", "Auth service validate failed", http.StatusBadGateway)
	registerError("auth_connection_id is required", "AUTH_CONNECTION_ID_REQUIRED", "Auth_connection_id is required", http.StatusBadRequest)
	registerError("base url must include scheme and host", "BASE_URL_MUST_INCLUDE_SCHEME_AND_HOST", "Base URL must include a scheme and host", http.StatusBadRequest)
	registerError("begin scan-control-plane db bootstrap", "BEGIN_SCAN_CONTROL_PLANE_DB_BOOTSTRAP", "Failed to begin the scan-control-plane database bootstrap", http.StatusInternalServerError)
	registerErrorPattern("binding %s sync mode does not support file events", "BINDING_SYNC_MODE_FILE_EVENTS_UNSUPPORTED", "The binding sync mode does not support file events", http.StatusBadRequest)
	registerError("binding does not belong to source", "BINDING_DOES_NOT_BELONG_TO_SOURCE", "The binding does not belong to the data source", http.StatusConflict)
	registerError("binding generation changed", "BINDING_GENERATION_CHANGED", "Binding generation changed", http.StatusConflict)
	registerError("binding identity is required", "BINDING_IDENTITY_REQUIRED", "Binding identity is required", http.StatusBadRequest)
	registerError("binding is not active", "BINDING_INACTIVE", "Data source binding is inactive", http.StatusConflict)
	registerError("binding target is already used by this source", "BINDING_TARGET_DUPLICATED", "Data source binding target is duplicated", http.StatusConflict)
	registerError("binding target is duplicated", "BINDING_TARGET_DUPLICATED", "Data source binding target is duplicated", http.StatusConflict)
	registerError("binding_generation must be positive", "BINDING_GENERATION_MUST_BE_POSITIVE", "Binding_generation must be positive", http.StatusBadRequest)
	registerError("binding_id is required when source has multiple bindings", "BINDING_ID_REQUIRED_WHEN_SOURCE_HAS_MULTIPLE_BINDINGS", "Binding_id is required when source has multiple bindings", http.StatusBadRequest)
	registerError("bindings: at least one binding is required", "BINDINGS_AT_LEAST_ONE_BINDING_REQUIRED", "Bindings: at least one binding is required", http.StatusBadRequest)
	registerError("calendar must be weekly", "CALENDAR_MUST_BE_WEEKLY", "Calendar must be weekly", http.StatusBadRequest)
	registerError("caller_id: required", "CALLER_ID_REQUIRED", "Caller_id is required", http.StatusBadRequest)
	registerError("chat_enabled is required", "CHAT_ENABLED_REQUIRED", "Chat_enabled is required", http.StatusBadRequest)
	registerError("commit scan-control-plane db bootstrap", "COMMIT_SCAN_CONTROL_PLANE_DB_BOOTSTRAP", "Failed to commit the scan-control-plane database bootstrap", http.StatusInternalServerError)
	registerErrorPattern("command_id: %s", "COMMAND_ID_INVALID", "Command_id is invalid", http.StatusBadRequest)
	registerError("compensation poll interval must be positive", "COMPENSATION_POLL_INTERVAL_MUST_BE_POSITIVE", "Compensation poll interval must be positive", http.StatusBadRequest)
	registerError("configure agent client", "CONFIGURE_AGENT_CLIENT", "Failed to configure the Agent client", http.StatusInternalServerError)
	registerError("configure auth service admin verifier", "CONFIGURE_AUTH_SERVICE_ADMIN_VERIFIER", "Failed to configure the auth service administrator verifier", http.StatusInternalServerError)
	registerError("configure auth service client", "CONFIGURE_AUTH_SERVICE_CLIENT", "Failed to configure the auth service client", http.StatusInternalServerError)
	registerError("configure core client", "CONFIGURE_CORE_CLIENT", "Failed to configure the Core service client", http.StatusInternalServerError)
	registerError("configure feishu client", "CONFIGURE_FEISHU_CLIENT", "Failed to configure the Feishu client", http.StatusInternalServerError)
	registerError("configure target search cache state redis", "CONFIGURE_TARGET_SEARCH_CACHE_STATE_REDIS", "Failed to configure Redis for target search cache state", http.StatusInternalServerError)
	registerError("configure target search cache state sqlite", "CONFIGURE_TARGET_SEARCH_CACHE_STATE_SQLITE", "Failed to configure SQLite for target search cache state", http.StatusInternalServerError)
	registerError("connector does not support search", "CONNECTOR_DOES_NOT_SUPPORT_SEARCH", "The connector does not support search", http.StatusBadRequest)
	registerError("connector is already registered", "CONNECTOR_IS_ALREADY_REGISTERED", "Connector is already registered", http.StatusConflict)
	registerError("connector is nil", "CONNECTOR_IS_NIL", "Connector is nil", http.StatusInternalServerError)
	registerError("connector is not registered", "CONNECTOR_NOT_FOUND", "Connector not found", http.StatusNotFound)
	registerError("connector registry is not configured", "CONNECTOR_REGISTRY_NOT_CONFIGURED", "Connector registry is not configured", http.StatusInternalServerError)
	registerError("connector_type does not match connector spec", "CONNECTOR_TYPE_DOES_NOT_MATCH_CONNECTOR_SPEC", "connector_type does not match the connector specification", http.StatusBadRequest)
	registerError("connector_type is required", "CONNECTOR_TYPE_REQUIRED", "Connector_type is required", http.StatusBadRequest)
	registerError("connector_type must be local_fs", "CONNECTOR_TYPE_MUST_BE_LOCAL_FS", "connector_type must be local_fs", http.StatusBadRequest)
	registerError("connector_type: required", "CONNECTOR_TYPE_REQUIRED", "Connector_type is required", http.StatusBadRequest)
	registerError("content store is required to open content_uri", "CONTENT_STORE_REQUIRED_TO_OPEN_CONTENT_URI", "Content store is required to open content_uri", http.StatusBadRequest)
	registerError("content_uri is not a valid file uri", "CONTENT_URI_IS_NOT_A_VALID_FILE_URI", "Content_uri is not a valid file uri", http.StatusBadRequest)
	registerError("content_uri is required", "CONTENT_URI_REQUIRED", "Content_uri is required", http.StatusBadRequest)
	registerError("content_uri must use file or scan-temp scheme", "CONTENT_URI_MUST_USE_FILE_OR_SCAN_TEMP_SCHEME", "Content_uri must use file or scan-temp scheme", http.StatusBadRequest)
	registerError("content_uri must use scan-temp scheme", "CONTENT_URI_MUST_USE_SCAN_TEMP_SCHEME", "Content_uri must use scan-temp scheme", http.StatusBadRequest)
	registerError("content_uri or content reader is required for create", "CONTENT_URI_OR_CONTENT_READER_REQUIRED_FOR_CREATE", "Content_uri or content reader is required for create", http.StatusBadRequest)
	registerError("content_uri or content reader is required for reparse", "CONTENT_URI_OR_CONTENT_READER_REQUIRED_FOR_REPARSE", "Content_uri or content reader is required for reparse", http.StatusBadRequest)
	registerError("core base url is required", "CORE_BASE_URL_REQUIRED", "Core base url is required", http.StatusBadRequest)
	registerError("core base url must include scheme and host", "CORE_BASE_URL_MUST_INCLUDE_SCHEME_AND_HOST", "Core service base URL must include a scheme and host", http.StatusBadRequest)
	registerError("core client does not support dataset deletion", "CORE_CLIENT_DOES_NOT_SUPPORT_DATASET_DELETION", "The Core service client does not support dataset deletion", http.StatusBadRequest)
	registerError("core create binding root returned empty document_id", "CORE_CREATE_BINDING_ROOT_RETURNED_EMPTY_DOCUMENT_ID", "Core service returned an empty document_id when creating the binding root", http.StatusBadGateway)
	registerError("core create task returned empty task_id", "CORE_CREATE_TASK_RETURNED_EMPTY_TASK_ID", "Core service returned an empty task_id when creating a task", http.StatusBadGateway)
	registerError("core result poll interval must be positive", "CORE_RESULT_POLL_INTERVAL_MUST_BE_POSITIVE", "Core result poll interval must be positive", http.StatusBadRequest)
	registerError("core result reconciler is required", "CORE_RESULT_RECONCILER_REQUIRED", "Core result reconciler is required", http.StatusBadRequest)
	registerError("core resume task returned empty tasks", "CORE_SUBMIT_FAILED", "Failed to submit task to core service", http.StatusBadGateway)
	registerError("core upload returned empty upload_file_id", "CORE_UPLOAD_RETURNED_EMPTY_UPLOAD_FILE_ID", "Core service returned an empty upload_file_id after upload", http.StatusBadGateway)
	registerError("core_task_not_found", "CORE_TASK_NOT_FOUND", "Core task not found", http.StatusNotFound)
	registerError("could not allocate temp object token", "COULD_NOT_ALLOCATE_TEMP_OBJECT_TOKEN", "Could not allocate temp object token", http.StatusInternalServerError)
	registerError("crawl list request interval must be non-negative", "CRAWL_LIST_REQUEST_INTERVAL_MUST_BE_NON_NEGATIVE", "Crawl list request interval must be non-negative", http.StatusBadRequest)
	registerError("crawl request kind is unsupported", "CRAWL_REQUEST_KIND_IS_UNSUPPORTED", "Crawl request kind is unsupported", http.StatusBadRequest)
	registerError("current level has more items than max_items", "CURRENT_LEVEL_HAS_MORE_ITEMS_THAN_MAX_ITEMS", "Current level has more items than max_items", http.StatusRequestEntityTooLarge)
	registerError("cursor is invalid", "CURSOR_IS_INVALID", "Cursor is invalid", http.StatusBadRequest)
	registerError("cursor must be empty for all_current_level", "CURSOR_MUST_BE_EMPTY_FOR_ALL_CURRENT_LEVEL", "Cursor must be empty for all_current_level", http.StatusBadRequest)
	registerError("dataset_id and core_task_id are required", "DATASET_ID_AND_CORE_TASK_ID_ARE_REQUIRED", "Dataset_id and core_task_id are required", http.StatusBadRequest)
	registerError("dataset_id and display_name are required", "DATASET_ID_AND_DISPLAY_NAME_ARE_REQUIRED", "Dataset_id and display_name are required", http.StatusBadRequest)
	registerError("dataset_id is required", "DATASET_ID_REQUIRED", "Dataset_id is required", http.StatusBadRequest)
	registerErrorPattern("days contains unsupported value %q", "SCHEDULE_DAY_UNSUPPORTED", "The schedule contains an unsupported day", http.StatusBadRequest)
	registerError("days must not be empty", "DAYS_MUST_NOT_BE_EMPTY", "Days must not be empty", http.StatusBadRequest)
	registerError("db driver must be postgres or sqlite", "DB_DRIVER_MUST_BE_POSTGRES_OR_SQLITE", "Db driver must be postgres or sqlite", http.StatusBadRequest)
	registerError("db dsn is required", "DB_DSN_REQUIRED", "Db dsn is required", http.StatusBadRequest)
	registerError("db job queue store is required", "DB_JOB_QUEUE_STORE_REQUIRED", "Db job queue store is required", http.StatusBadRequest)
	registerError("db opener is required for sql repository", "DB_OPENER_REQUIRED_FOR_SQL_REPOSITORY", "A database opener is required for the SQL repository", http.StatusBadRequest)
	registerError("decode feishu api data failed", "DECODE_FEISHU_API_DATA_FAILED", "Decode feishu api data failed", http.StatusBadGateway)
	registerError("decode feishu api response failed", "DECODE_FEISHU_API_RESPONSE_FAILED", "Decode feishu api response failed", http.StatusBadGateway)
	registerErrorPattern("decode notion api %s response failed", "DECODE_NOTION_API_RESPONSE_FAILED", "Failed to decode the Notion API response", http.StatusBadGateway)
	registerError("default dataset algo id is required", "DEFAULT_DATASET_ALGO_ID_REQUIRED", "Default dataset algo id is required", http.StatusBadRequest)
	registerError("default dataset algo name is required", "DEFAULT_DATASET_ALGO_NAME_REQUIRED", "Default dataset algo name is required", http.StatusBadRequest)
	registerError("delete task is obsolete", "DELETE_TASK_IS_OBSOLETE", "Delete task is obsolete", http.StatusConflict)
	registerError("delta crawl is not supported", "UNSUPPORTED_DELTA", "Incremental synchronization is not supported", http.StatusBadRequest)
	registerError("display_name is required", "DISPLAY_NAME_REQUIRED", "Display_name is required", http.StatusBadRequest)
	registerError("document changed", "DOCUMENT_CHANGED", "Document changed", http.StatusConflict)
	registerError("document state generation is stale", "DOCUMENT_STATE_GENERATION_IS_STALE", "Document state generation is stale", http.StatusConflict)
	registerError("document state has no pending action", "DOCUMENT_STATE_HAS_NO_PENDING_ACTION", "The document state has no pending action", http.StatusConflict)
	registerError("document_id is required", "DOCUMENT_ID_REQUIRED", "Document_id is required", http.StatusBadRequest)
	registerError("drive file export_format is not supported", "UNSUPPORTED_EXPORT_FORMAT", "The requested export format is not supported", http.StatusBadRequest)
	registerError("drive object is not found in target", "DRIVE_OBJECT_IS_NOT_FOUND_IN_TARGET", "The drive object was not found in the target", http.StatusNotFound)
	registerError("drive shortcut target is missing", "DRIVE_SHORTCUT_TARGET_IS_MISSING", "The drive shortcut target is missing", http.StatusInternalServerError)
	registerError("drive token is required", "DRIVE_TOKEN_REQUIRED", "Drive token is required", http.StatusBadRequest)
	registerErrorPattern("drop legacy scan-control-plane table %s", "DROP_LEGACY_SCAN_CONTROL_PLANE_TABLE_FAILED", "Failed to drop a legacy scan-control-plane table", http.StatusInternalServerError)
	registerError("ensure scan-control-plane migration marker table", "ENSURE_SCAN_CONTROL_PLANE_MIGRATION_MARKER_TABLE", "Failed to ensure the scan-control-plane migration marker table", http.StatusInternalServerError)
	registerError("export_format is not supported", "UNSUPPORTED_EXPORT_FORMAT", "The requested export format is not supported", http.StatusBadRequest)
	registerError("exported version changed", "EXPORTED_VERSION_CHANGED", "Exported version changed", http.StatusConflict)
	registerError("exported version does not match requested source_version", "EXPORTED_VERSION_DOES_NOT_MATCH_REQUESTED_SOURCE_VERSION", "The exported version does not match the requested source_version", http.StatusBadRequest)
	registerError("feishu api returned non-json response", "FEISHU_API_RETURNED_NON_JSON_RESPONSE", "Feishu API returned a non-JSON response", http.StatusBadGateway)
	registerError("feishu base url is required", "FEISHU_BASE_URL_REQUIRED", "Feishu base url is required", http.StatusBadRequest)
	registerError("feishu clients are not configured", "FEISHU_CLIENTS_ARE_NOT_CONFIGURED", "Feishu clients are not configured", http.StatusInternalServerError)
	registerError("feishu delta fetch is not supported", "UNSUPPORTED_DELTA", "Incremental synchronization is not supported", http.StatusBadRequest)
	registerError("feishu pagination cursor is empty", "FEISHU_PAGINATION_CURSOR_IS_EMPTY", "Feishu pagination cursor is empty", http.StatusBadGateway)
	registerError("file uri must be local", "FILE_URI_MUST_BE_LOCAL", "File uri must be local", http.StatusBadRequest)
	registerError("generate tasks max objects per request must be positive", "GENERATE_TASKS_MAX_OBJECTS_PER_REQUEST_MUST_BE_POSITIVE", "Generate tasks max objects per request must be positive", http.StatusBadRequest)
	registerError("idempotency_key, dataset_id, and name are required", "IDEMPOTENCY_KEY_DATASET_ID_AND_NAME_ARE_REQUIRED", "Idempotency_key, dataset_id, and name are required", http.StatusBadRequest)
	registerError("idempotency_key, name, and created_by are required", "IDEMPOTENCY_KEY_NAME_AND_CREATED_BY_ARE_REQUIRED", "Idempotency_key, name, and created_by are required", http.StatusBadRequest)
	registerError("invalid agent token", "INVALID_AGENT_TOKEN", "Invalid agent token", http.StatusUnauthorized)
	registerError("invalid json request body", "INVALID_JSON_REQUEST_BODY", "Invalid JSON request body", http.StatusBadRequest)
	registerError("invalid scan temp token", "INVALID_SCAN_TEMP_TOKEN", "Invalid scan temporary token", http.StatusBadRequest)
	registerError("invalid scan temp uri", "INVALID_SCAN_TEMP_URI", "Invalid scan temporary URI", http.StatusBadRequest)
	registerError("invalid time token", "INVALID_TIME_TOKEN", "Invalid time token", http.StatusBadRequest)
	registerError("keyword is required", "KEYWORD_REQUIRED", "Keyword is required", http.StatusBadRequest)
	registerError("list scan-control-plane columns", "LIST_SCAN_CONTROL_PLANE_COLUMNS", "Failed to list scan-control-plane columns", http.StatusInternalServerError)
	registerError("list scan-control-plane tables", "LIST_SCAN_CONTROL_PLANE_TABLES", "Failed to list scan-control-plane tables", http.StatusInternalServerError)
	registerError("list_mode is not supported", "UNSUPPORTED_LIST_MODE", "List mode is not supported", http.StatusBadRequest)
	registerError("list_mode is not supported for search", "LIST_MODE_UNSUPPORTED_FOR_SEARCH", "list_mode is not supported for search", http.StatusBadRequest)
	registerError("local data sources can only be accessed by administrators", "LOCAL_DATA_SOURCES_CAN_ONLY_BE_ACCESSED_BY_ADMINISTRATORS", "Local data sources can only be accessed by administrators", http.StatusForbidden)
	registerError("local_fs agent client is not configured", "LOCAL_FS_AGENT_CLIENT_NOT_CONFIGURED", "Local_fs agent client is not configured", http.StatusInternalServerError)
	registerError("local_fs delta fetch is not supported", "UNSUPPORTED_DELTA", "Incremental synchronization is not supported", http.StatusBadRequest)
	registerError("local_fs pagination cursor is empty", "LOCAL_FS_PAGINATION_CURSOR_IS_EMPTY", "Local_fs pagination cursor is empty", http.StatusBadGateway)
	registerError("local_fs root pagination cursor is empty", "LOCAL_FS_ROOT_PAGINATION_CURSOR_IS_EMPTY", "Local_fs root pagination cursor is empty", http.StatusBadGateway)
	registerError("local_fs target search cache prewarm failed", "LOCAL_FS_TARGET_SEARCH_CACHE_PREWARM_FAILED", "Local_fs target search cache prewarm failed", http.StatusBadGateway)
	registerError("lock scan-control-plane db bootstrap", "LOCK_SCAN_CONTROL_PLANE_DB_BOOTSTRAP", "Failed to lock the scan-control-plane database bootstrap", http.StatusInternalServerError)
	registerError("marshal openapi yaml failed", "MARSHAL_OPENAPI_YAML_FAILED", "Marshal openapi yaml failed", http.StatusInternalServerError)
	registerError("max_items exceeds service limit", "MAX_ITEMS_EXCEEDS_SERVICE_LIMIT", "Max_items exceeds service limit", http.StatusBadRequest)
	registerError("max_items is required for all_current_level", "MAX_ITEMS_REQUIRED_FOR_ALL_CURRENT_LEVEL", "Max_items is required for all_current_level", http.StatusBadRequest)
	registerError("max_page_size must be positive", "MAX_PAGE_SIZE_MUST_BE_POSITIVE", "Max_page_size must be positive", http.StatusBadRequest)
	registerError("migrate sqlite repository", "MIGRATE_SQLITE_REPOSITORY", "Failed to migrate the SQLite repository", http.StatusInternalServerError)
	registerError("missing caller", "MISSING_CALLER", "Missing caller", http.StatusUnauthorized)
	registerError("must be a json object", "MUST_BE_A_JSON_OBJECT", "Must be a json object", http.StatusBadRequest)
	registerError("must use hh:mm:ss", "MUST_USE_HH_MM_SS", "Must use hh:mm:ss", http.StatusBadRequest)
	registerError("name: required", "NAME_REQUIRED", "Name is required", http.StatusBadRequest)
	registerError("name: supports chinese/english, numbers, -, _, ., up to 100 characters", "NAME_SUPPORTS_CHINESE_ENGLISH_NUMBERS_UP_TO_100_CHARACTERS", "Name: supports chinese/english, numbers, -, _, ., up to 100 characters", http.StatusBadRequest)
	registerError("no due parse task", "NO_DUE_PARSE_TASK", "No parse task is due", http.StatusNotFound)
	registerErrorPattern("notion api %s returned %d", "NOTION_API_REQUEST_FAILED", "The Notion API request failed", http.StatusBadGateway)
	registerError("notion delta fetch is not supported", "UNSUPPORTED_DELTA", "Incremental synchronization is not supported", http.StatusBadRequest)
	registerError("notion export content is empty", "NOTION_EXPORT_CONTENT_IS_EMPTY", "Notion export content is empty", http.StatusBadRequest)
	registerError("notion object id is required", "NOTION_OBJECT_ID_REQUIRED", "Notion object id is required", http.StatusBadRequest)
	registerError("object is not exportable", "OBJECT_IS_NOT_EXPORTABLE", "The object cannot be exported", http.StatusBadRequest)
	registerError("object is not selectable", "OBJECT_IS_NOT_SELECTABLE", "The object cannot be selected", http.StatusBadRequest)
	registerError("object_key does not include a local path", "OBJECT_KEY_DOES_NOT_INCLUDE_A_LOCAL_PATH", "object_key does not include a local path", http.StatusInternalServerError)
	registerError("object_key is required", "OBJECT_KEY_REQUIRED", "Object_key is required", http.StatusBadRequest)
	registerError("open sql repository", "OPEN_SQL_REPOSITORY", "Failed to open the SQL repository", http.StatusInternalServerError)
	registerError("page_size exceeds connector max_page_size", "PAGE_SIZE_EXCEEDS_CONNECTOR_MAX_PAGE_SIZE", "Page_size exceeds connector max_page_size", http.StatusBadRequest)
	registerError("page_size must be positive", "PAGE_SIZE_MUST_BE_POSITIVE", "Page_size must be positive", http.StatusBadRequest)
	registerError("parent_document_id is required for create", "PARENT_DOCUMENT_ID_REQUIRED_FOR_CREATE", "Parent_document_id is required for create", http.StatusBadRequest)
	registerError("parse batch object limit exceeded", "PARSE_BATCH_OBJECT_LIMIT_EXCEEDED", "Parse batch object limit exceeded", http.StatusBadRequest)
	registerError("parse dead letter after must be positive", "PARSE_DEAD_LETTER_AFTER_MUST_BE_POSITIVE", "Parse dead letter after must be positive", http.StatusBadRequest)
	registerError("parse task generation is stale", "PARSE_TASK_GENERATION_IS_STALE", "Parse task generation is stale", http.StatusConflict)
	registerError("parse task idempotency_key, dataset_id, display_name, and action are required", "PARSE_TASK_IDEMPOTENCY_KEY_DATASET_ID_DISPLAY_NAME_AND_ACTION_ARE_REQUIRED", "Parse task idempotency_key, dataset_id, display_name, and action are required", http.StatusBadRequest)
	registerError("parse task is not retryable", "TASK_NOT_RETRYABLE", "Task cannot be retried", http.StatusConflict)
	registerError("parse task is obsolete", "PARSE_TASK_IS_OBSOLETE", "Parse task is obsolete", http.StatusConflict)
	registerError("parse task query is not configured", "PARSE_TASK_QUERY_NOT_CONFIGURED", "Parse task query is not configured", http.StatusInternalServerError)
	registerError("parse worker global concurrency must be positive", "PARSE_WORKER_GLOBAL_CONCURRENCY_MUST_BE_POSITIVE", "Parse worker global concurrency must be positive", http.StatusBadRequest)
	registerError("parse worker is required", "PARSE_WORKER_REQUIRED", "Parse worker is required", http.StatusBadRequest)
	registerError("parse worker source concurrency must be positive", "PARSE_WORKER_SOURCE_CONCURRENCY_MUST_BE_POSITIVE", "Parse worker source concurrency must be positive", http.StatusBadRequest)
	registerError("path is outside local_fs public root", "PATH_IS_OUTSIDE_LOCAL_FS_PUBLIC_ROOT", "Path is outside local_fs public root", http.StatusBadRequest)
	registerError("port must be between 1 and 65535", "PORT_MUST_BE_BETWEEN_1_AND_65535", "Port must be between 1 and 65535", http.StatusBadRequest)
	registerError("provider object kind is required", "PROVIDER_OBJECT_KIND_REQUIRED", "Provider object kind is required", http.StatusBadRequest)
	registerError("provider object kind is unsupported", "PROVIDER_OBJECT_KIND_IS_UNSUPPORTED", "Provider object kind is unsupported", http.StatusBadRequest)
	registerErrorPattern("provider option %s is required", "PROVIDER_OPTION_REQUIRED", "A required provider option is missing", http.StatusBadRequest)
	registerError("provider token is required", "PROVIDER_TOKEN_REQUIRED", "Provider token is required", http.StatusBadRequest)
	registerErrorPattern("read scan-control-plane baseline migration %s", "READ_SCAN_CONTROL_PLANE_BASELINE_MIGRATION_FAILED", "Failed to read the scan-control-plane baseline migration", http.StatusInternalServerError)
	registerError("read scan-control-plane migration marker", "READ_SCAN_CONTROL_PLANE_MIGRATION_MARKER", "Failed to read the scan-control-plane migration marker", http.StatusInternalServerError)
	registerError("record scan-control-plane migration marker", "RECORD_SCAN_CONTROL_PLANE_MIGRATION_MARKER", "Failed to record the scan-control-plane migration marker", http.StatusInternalServerError)
	registerError("redis ping failed", "REDIS_PING_FAILED", "Redis ping failed", http.StatusServiceUnavailable)
	registerError("redis url must not be configured when lazymind_state_backend=sqlite", "REDIS_URL_MUST_NOT_BE_CONFIGURED_WHEN_LAZYMIND_STATE_BACKEND_SQLITE", "Redis url must not be configured when lazymind_state_backend=sqlite", http.StatusBadRequest)
	registerError("redis url scheme must be redis", "REDIS_URL_SCHEME_MUST_BE_REDIS", "Redis url scheme must be redis", http.StatusBadRequest)
	registerError("request_id is already in progress", "REQUEST_ID_IS_ALREADY_IN_PROGRESS", "A request with this request_id is already in progress", http.StatusConflict)
	registerError("request_id was reused with a different payload", "REQUEST_ID_WAS_REUSED_WITH_A_DIFFERENT_PAYLOAD", "request_id was reused with a different payload", http.StatusConflict)
	registerError("request_id: required", "REQUEST_ID_REQUIRED", "Request_id is required", http.StatusBadRequest)
	registerErrorPattern("result_json: %s", "RESULT_JSON_INVALID", "Result JSON is invalid", http.StatusBadRequest)
	registerError("rules must not be empty", "RULES_MUST_NOT_BE_EMPTY", "Rules must not be empty", http.StatusBadRequest)
	registerErrorPattern("rules[%d].%s", "SCHEDULE_RULE_INVALID", "A schedule rule is invalid", http.StatusBadRequest)
	registerError("scan scan-control-plane column", "SCAN_SCAN_CONTROL_PLANE_COLUMN", "Failed to scan a scan-control-plane column", http.StatusInternalServerError)
	registerError("scan scan-control-plane columns", "SCAN_SCAN_CONTROL_PLANE_COLUMNS", "Failed to scan scan-control-plane columns", http.StatusInternalServerError)
	registerError("scan scan-control-plane table", "SCAN_SCAN_CONTROL_PLANE_TABLE", "Failed to scan a scan-control-plane table", http.StatusInternalServerError)
	registerError("scan scan-control-plane tables", "SCAN_SCAN_CONTROL_PLANE_TABLES", "Failed to scan scan-control-plane tables", http.StatusInternalServerError)
	registerError("scan temp object not found", "SCAN_TEMP_OBJECT_NOT_FOUND", "Scan temp object not found", http.StatusNotFound)
	registerError("schedule engine is not configured", "SCHEDULE_ENGINE_NOT_CONFIGURED", "Schedule engine is not configured", http.StatusInternalServerError)
	registerErrorPattern("schedule policy produced no next sync time within %d days", "SCHEDULE_NEXT_SYNC_TIME_NOT_FOUND", "The schedule policy produced no next synchronization time", http.StatusBadRequest)
	registerError("schedule_policy is invalid", "SCHEDULE_POLICY_INVALID", "Schedule policy is invalid", http.StatusBadRequest)
	registerError("schedule_policy is required", "SCHEDULE_POLICY_REQUIRED", "Schedule_policy is required", http.StatusBadRequest)
	registerError("schedule_policy must be valid json", "SCHEDULE_POLICY_MUST_BE_VALID_JSON", "Schedule_policy must be valid json", http.StatusBadRequest)
	registerErrorPattern("schedule_policy: %s", "SCHEDULE_POLICY_INVALID", "Schedule policy is invalid", http.StatusBadRequest)
	registerError("schedule_policy: required for scheduled sync", "SCHEDULE_POLICY_REQUIRED_FOR_SCHEDULED_SYNC", "Schedule_policy: required for scheduled sync", http.StatusBadRequest)
	registerError("scope_type is not supported", "SCOPE_TYPE_UNSUPPORTED", "Scope_type is not supported", http.StatusBadRequest)
	registerError("source config_version does not match", "SOURCE_VERSION_CONFLICT", "Data source version conflict", http.StatusConflict)
	registerError("source document query is not configured", "SOURCE_DOCUMENT_QUERY_NOT_CONFIGURED", "Source document query is not configured", http.StatusInternalServerError)
	registerError("source engine is not configured", "SOURCE_ENGINE_NOT_CONFIGURED", "Source engine is not configured", http.StatusInternalServerError)
	registerError("source is not active", "SOURCE_IS_NOT_ACTIVE", "Source is not active", http.StatusConflict)
	registerError("source read refresh failed", "SOURCE_READ_REFRESH_FAILED", "Source read refresh failed", http.StatusBadGateway)
	registerError("source tree connector registry is not configured", "SOURCE_TREE_CONNECTOR_REGISTRY_NOT_CONFIGURED", "Source tree connector registry is not configured", http.StatusInternalServerError)
	registerError("source tree query engine is not configured", "SOURCE_TREE_QUERY_ENGINE_NOT_CONFIGURED", "Source tree query engine is not configured", http.StatusInternalServerError)
	registerError("source version changed", "SOURCE_VERSION_CHANGED", "Source version changed", http.StatusConflict)
	registerError("source_document_id is required for delete", "SOURCE_DOCUMENT_ID_REQUIRED_FOR_DELETE", "Source_document_id is required for delete", http.StatusBadRequest)
	registerError("source_document_id is required for reparse", "SOURCE_DOCUMENT_ID_REQUIRED_FOR_REPARSE", "Source_document_id is required for reparse", http.StatusBadRequest)
	registerError("source_id is required", "SOURCE_ID_REQUIRED", "Source_id is required", http.StatusBadRequest)
	registerError("source_id: required", "SOURCE_ID_REQUIRED", "Source_id is required", http.StatusBadRequest)
	registerError("source_version is required", "SOURCE_VERSION_REQUIRED", "Source_version is required", http.StatusBadRequest)
	registerError("space_id is required", "SPACE_ID_REQUIRED", "Space_id is required", http.StatusBadRequest)
	registerError("state generation changed", "STATE_GENERATION_CHANGED", "State generation changed", http.StatusConflict)
	registerError("status: unsupported", "STATUS_UNSUPPORTED", "Status is not supported", http.StatusBadRequest)
	registerError("superseded", "TASK_SUPERSEDED", "Task has been superseded", http.StatusConflict)
	registerError("sync run coverage is incomplete", "SYNC_RUN_COVERAGE_IS_INCOMPLETE", "Synchronization run coverage is incomplete", http.StatusConflict)
	registerError("sync run did not succeed", "SYNC_RUN_DID_NOT_SUCCEED", "The synchronization run did not succeed", http.StatusConflict)
	registerError("sync run does not match source binding", "SYNC_RUN_DOES_NOT_MATCH_SOURCE_BINDING", "The synchronization run does not match the data source binding", http.StatusConflict)
	registerError("sync run generation is stale", "SYNC_RUN_GENERATION_IS_STALE", "Sync run generation is stale", http.StatusConflict)
	registerError("sync_mode: required", "SYNC_MODE_REQUIRED", "Sync_mode is required", http.StatusBadRequest)
	registerError("sync_mode: unsupported", "SYNC_MODE_UNSUPPORTED", "sync_mode is not supported", http.StatusBadRequest)
	registerError("target cache pagination cursor did not advance", "TARGET_CACHE_PAGINATION_CURSOR_DID_NOT_ADVANCE", "Target cache pagination cursor did not advance", http.StatusBadGateway)
	registerError("target cache pagination cursor is empty", "TARGET_CACHE_PAGINATION_CURSOR_IS_EMPTY", "Target cache pagination cursor is empty", http.StatusBadGateway)
	registerError("target path is not readable", "TARGET_PATH_IS_NOT_READABLE", "Target path is not readable", http.StatusBadRequest)
	registerError("target path is outside allowed prefixes", "TARGET_PATH_IS_OUTSIDE_ALLOWED_PREFIXES", "Target path is outside allowed prefixes", http.StatusBadRequest)
	registerError("target path is outside local_fs public root", "TARGET_PATH_IS_OUTSIDE_LOCAL_FS_PUBLIC_ROOT", "Target path is outside local_fs public root", http.StatusBadRequest)
	registerError("target path must be absolute after agent normalization", "TARGET_PATH_MUST_BE_ABSOLUTE_AFTER_AGENT_NORMALIZATION", "Target path must be absolute after agent normalization", http.StatusBadRequest)
	registerError("target path was not found", "TARGET_PATH_WAS_NOT_FOUND", "Target path was not found", http.StatusNotFound)
	registerError("target search cache build failed", "TARGET_SEARCH_CACHE_BUILD_FAILED", "Target search cache build failed", http.StatusBadGateway)
	registerError("target search cache prewarm failed", "TARGET_SEARCH_CACHE_PREWARM_FAILED", "Target search cache prewarm failed", http.StatusBadGateway)
	registerError("target search cache prewarm interval must be positive", "TARGET_SEARCH_CACHE_PREWARM_INTERVAL_MUST_BE_POSITIVE", "Target search cache prewarm interval must be positive", http.StatusBadRequest)
	registerError("target search cache prewarm stagger must be positive", "TARGET_SEARCH_CACHE_PREWARM_STAGGER_MUST_BE_POSITIVE", "Target search cache prewarm stagger must be positive", http.StatusBadRequest)
	registerError("target tree engine is not configured", "TARGET_TREE_ENGINE_NOT_CONFIGURED", "Target tree engine is not configured", http.StatusInternalServerError)
	registerError("target_ref is required", "TARGET_REF_REQUIRED", "Target_ref is required", http.StatusBadRequest)
	registerError("target_ref: required", "TARGET_REF_REQUIRED", "Target_ref is required", http.StatusBadRequest)
	registerError("target_type is not supported", "TARGET_TYPE_UNSUPPORTED", "Target_type is not supported", http.StatusBadRequest)
	registerError("target_type: required", "TARGET_TYPE_REQUIRED", "Target_type is required", http.StatusBadRequest)
	registerError("target_types is required", "TARGET_TYPES_REQUIRED", "Target_types is required", http.StatusBadRequest)
	registerError("task planner is not configured", "TASK_PLANNER_NOT_CONFIGURED", "Task planner is not configured", http.StatusInternalServerError)
	registerError("task was replaced", "TASK_WAS_REPLACED", "Task was replaced", http.StatusConflict)
	registerError("temp dir is required", "TEMP_DIR_REQUIRED", "Temp dir is required", http.StatusBadRequest)
	registerError("temp object reader is required", "TEMP_OBJECT_READER_REQUIRED", "Temp object reader is required", http.StatusBadRequest)
	registerError("temp object store is nil", "TEMP_OBJECT_STORE_IS_NIL", "Temp object store is nil", http.StatusInternalServerError)
	registerError("temp object store is required for feishu export", "TEMP_OBJECT_STORE_REQUIRED_FOR_FEISHU_EXPORT", "Temporary object storage is required for Feishu export", http.StatusBadRequest)
	registerError("temp object store is required for local_fs export", "TEMP_OBJECT_STORE_REQUIRED_FOR_LOCAL_FS_EXPORT", "Temporary object storage is required for local_fs export", http.StatusBadRequest)
	registerError("temp object store is required for notion export", "TEMP_OBJECT_STORE_REQUIRED_FOR_NOTION_EXPORT", "Temporary object storage is required for Notion export", http.StatusBadRequest)
	registerError("temp ttl must be positive", "TEMP_TTL_MUST_BE_POSITIVE", "Temp ttl must be positive", http.StatusBadRequest)
	registerErrorPattern("time %s", "SCHEDULE_TIME_INVALID", "Schedule time is invalid", http.StatusBadRequest)
	registerError("timezone is required", "TIMEZONE_REQUIRED", "Timezone is required", http.StatusBadRequest)
	registerErrorPattern("unexpected status %d", "UNEXPECTED_HTTP_STATUS", "The upstream service returned an unexpected HTTP status", http.StatusInternalServerError)
	registerError("unknown scan-control-plane database schema detected; refusing to reset automatically", "UNKNOWN_SCAN_CONTROL_PLANE_DATABASE_SCHEMA_DETECTED_REFUSING_TO_RESET_AUTOMATICALLY", "Unknown scan-control-plane database schema detected; refusing to reset automatically", http.StatusInternalServerError)
	registerErrorPattern("unsupported connector type %q", "CONNECTOR_TYPE_UNSUPPORTED", "Connector type is not supported", http.StatusBadRequest)
	registerErrorPattern("unsupported parse action %s", "PARSE_ACTION_UNSUPPORTED", "Parse action is not supported", http.StatusBadRequest)
	registerErrorPattern("unsupported scan-control-plane database state %q", "SCAN_CONTROL_PLANE_DATABASE_STATE_UNSUPPORTED", "The scan-control-plane database state is not supported", http.StatusBadRequest)
	registerErrorPattern("unsupported schedule timezone %q", "SCHEDULE_TIMEZONE_UNSUPPORTED", "Schedule timezone is not supported", http.StatusBadRequest)
	registerErrorPattern("unsupported target search cache state backend %q", "TARGET_SEARCH_CACHE_STATE_BACKEND_UNSUPPORTED", "Target search cache state backend is not supported", http.StatusBadRequest)
	registerError("user_id is required", "USER_ID_REQUIRED", "User_id is required", http.StatusBadRequest)
	registerError("wiki export_format is not supported", "UNSUPPORTED_EXPORT_FORMAT", "The requested export format is not supported", http.StatusBadRequest)
	registerError("wiki node ref is invalid", "WIKI_NODE_REF_IS_INVALID", "Wiki node ref is invalid", http.StatusBadRequest)
	registerError("wiki space is not found", "WIKI_SPACE_IS_NOT_FOUND", "Wiki space is not found", http.StatusNotFound)
	registerError("wiki space_id and node token are required", "WIKI_SPACE_ID_AND_NODE_TOKEN_ARE_REQUIRED", "Wiki space_id and node token are required", http.StatusBadRequest)
	registerError("wiki space_id is required", "WIKI_SPACE_ID_REQUIRED", "Wiki space_id is required", http.StatusBadRequest)
	registerError("wiki spaces pagination cursor is empty", "WIKI_SPACES_PAGINATION_CURSOR_IS_EMPTY", "Wiki spaces pagination cursor is empty", http.StatusBadGateway)
	registerError("wiki target_ref must include space_id and node_token", "WIKI_TARGET_REF_MUST_INCLUDE_SPACE_ID_AND_NODE_TOKEN", "Wiki target_ref must include space_id and node_token", http.StatusBadRequest)
	registerError("worker lease ttl must be positive", "WORKER_LEASE_TTL_MUST_BE_POSITIVE", "Worker lease ttl must be positive", http.StatusBadRequest)
	registerError("worker max backoff must be positive", "WORKER_MAX_BACKOFF_MUST_BE_POSITIVE", "Worker max backoff must be positive", http.StatusBadRequest)
	registerError("worker poll interval must be positive", "WORKER_POLL_INTERVAL_MUST_BE_POSITIVE", "Worker poll interval must be positive", http.StatusBadRequest)

	registerError("access store is not configured", "ACCESS_STORE_NOT_CONFIGURED", "Access store is not configured", http.StatusInternalServerError)
	registerError("access denied", "FORBIDDEN", "Forbidden", http.StatusForbidden)
	registerError("agent is not available", "AGENT_NOT_AVAILABLE", "Agent is not available", http.StatusServiceUnavailable)
	registerError("document state not found", "DOCUMENT_STATE_NOT_FOUND", "Document state not found", http.StatusNotFound)
	registerError("operation not found", "OPERATION_NOT_FOUND", "Operation not found", http.StatusNotFound)
	registerError("operation compensation is not retryable", "OPERATION_COMPENSATION_NOT_RETRYABLE", "Operation compensation cannot be retried", http.StatusConflict)
	registerError("dead letter not found", "DEAD_LETTER_NOT_FOUND", "Dead-letter task not found", http.StatusNotFound)
	registerError("orm repository is not initialized", "ORM_REPOSITORY_NOT_INITIALIZED", "Database repository is not initialized", http.StatusInternalServerError)
	registerError("agent not found", "AGENT_NOT_FOUND", "Agent not found", http.StatusNotFound)
	registerError("agent command not found", "AGENT_COMMAND_NOT_FOUND", "Agent command not found", http.StatusNotFound)
	registerError("binding not found", "BINDING_NOT_FOUND", "Data source binding not found", http.StatusNotFound)
	registerError("binding is not deleting", "BINDING_NOT_DELETING", "Data source binding is not being deleted", http.StatusConflict)
	registerError("binding cleanup is still pending", "BINDING_CLEANUP_PENDING", "Data source binding cleanup is still pending", http.StatusConflict)
	registerError("sync checkpoint not found", "SYNC_CHECKPOINT_NOT_FOUND", "Synchronization checkpoint not found", http.StatusNotFound)
	registerError("sync checkpoint generation is stale", "SYNC_CHECKPOINT_GENERATION_STALE", "Synchronization checkpoint generation is stale", http.StatusConflict)
	registerError("binding generation is stale", "BINDING_GENERATION_STALE", "Data source binding generation is stale", http.StatusConflict)
	registerError("binding_id is required", "BINDING_ID_REQUIRED", "binding_id is required", http.StatusInternalServerError)
	registerError("tree_key is required", "TREE_KEY_REQUIRED", "tree_key is required", http.StatusInternalServerError)
	registerError("search_name is required", "SEARCH_NAME_REQUIRED", "search_name is required", http.StatusInternalServerError)
	registerError("object parent cannot be itself", "OBJECT_PARENT_SELF_REFERENCE", "A source object cannot be its own parent", http.StatusInternalServerError)
	registerErrorPattern("root object depth must be 0: %s", "ROOT_OBJECT_DEPTH_INVALID", "Root source object depth must be 0", http.StatusInternalServerError)
	registerErrorPattern("child object depth must be positive: %s", "CHILD_OBJECT_DEPTH_INVALID", "Child source object depth must be positive", http.StatusInternalServerError)
	registerError("object not found", "OBJECT_NOT_FOUND", "Source object not found", http.StatusNotFound)
	registerError("sync run not found", "SYNC_RUN_NOT_FOUND", "Synchronization run not found", http.StatusNotFound)
	registerError("source not found", "SOURCE_NOT_FOUND", "Data source not found", http.StatusNotFound)
	registerError("document state insert was not visible", "DOCUMENT_STATE_INSERT_NOT_VISIBLE", "Inserted document state is not visible", http.StatusInternalServerError)
	registerError("document not found", "DOCUMENT_NOT_FOUND", "Document not found", http.StatusNotFound)
	registerError("parse task not found", "TASK_NOT_FOUND", "Task not found", http.StatusNotFound)
	registerError("core internal token is not configured", "CORE_INTERNAL_TOKEN_NOT_CONFIGURED", "Core internal token is not configured", http.StatusInternalServerError)
	registerError("batch get dataset usage", "DATASET_USAGE_BATCH_FAILED", "Failed to query dataset usage", http.StatusBadGateway)
}
