// Package plugin EventLoop handles workflow_step task lifecycle on the Go side.
// It extends handleTaskCreated in chat/conversation_logic.go to process
// agent_type='workflow_step' events with Workflow-specific session management.
package workflow

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"sort"
	"strings"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"lazymind/core/common"
	"lazymind/core/common/orm"
	"lazymind/core/modelconfig"
	"lazymind/core/state"
	"lazymind/core/store"
	"lazymind/core/subagent"
	"lazymind/core/taskcenter"
)

type chatStatusCacheEntry struct {
	Status string `json:"status"`
}

// WorkflowStepParams is the shared launch payload used by the v2 transition
// handler and the isolated pre-v2 task_created compatibility entry point.
type WorkflowStepParams struct {
	WorkflowID  string `json:"workflow_id"`
	WorkflowRef string `json:"workflow_ref,omitempty"`
	RevisionID  string `json:"revision_id,omitempty"`
	RevisionNo  int64  `json:"revision_no,omitempty"`
	TreeHash    string `json:"tree_hash,omitempty"`
	RemoteRoot  string `json:"remote_root,omitempty"`
	StepID      string `json:"step_id"`
	SessionID   string `json:"session_id"`
	UserInput   string `json:"user_input"`
	IsColdStart bool   `json:"is_cold_start"`
	HandOff     *bool  `json:"hand_off,omitempty"`
	PreflightID string `json:"preflight_id,omitempty"`

	// ChatSessionID identifies the ChatAgent turn for task lifecycle context.
	ChatSessionID string `json:"chat_session_id,omitempty"`
	// TraceID and ParentSpanID continue the ChatAgent trace in dispatched SubAgent.
	TraceID      string `json:"trace_id,omitempty"`
	ParentSpanID string `json:"parent_span_id,omitempty"`

	// WorkflowMode is "auto" | "dynamic" — resolved from the conversation request and
	// persisted into params so that OnSubAgentDone can branch correctly even when
	// reconstructing WorkflowChatContext from the DB (hooks.go path).
	WorkflowMode string `json:"workflow_mode,omitempty"`

	// RetryHint is a runtime instruction generated by ChatAgent for partial/full retries.
	// It is appended to the step objective before the SubAgent runs, and is NOT persisted
	// back to state.yml — it only affects the current execution.
	RetryHint string `json:"retry_hint,omitempty"`

	// PartialIndices maps slot → list of list_index values that should be
	// overwritten (not appended) when the SubAgent saves those artifacts.
	// Nil / empty means full write (append for list, overwrite for single).
	// Example: {"material_images": [1]} — only slot entry at list_index=1 is replaced.
	PartialIndices map[string][]int `json:"partial_indices,omitempty"`

	// HistoryFilesPerTurn carries the full per-turn user attachment index so the
	// SubAgent can access uploaded files via read_user_attachment / find_user_attachment.
	// Key = conversation turn sequence (string), value = list of absolute file paths.
	HistoryFilesPerTurn map[string][]string `json:"history_files_per_turn,omitempty"`
	ParentAgenticConfig map[string]any      `json:"parent_agentic_config,omitempty"`

	// Filters carries retrieval filters (e.g. kb_id) from the chat session into plugin steps.
	Filters map[string]any `json:"filters,omitempty"`

	// UserID is the chat user id for KB ACL and signed static-file URLs.
	UserID string `json:"user_id,omitempty"`

	// RequiredOutputs is compiled by Go. Outputs not listed here are valid
	// conditional products but do not gate attempt success.
	RequiredOutputs []string `json:"required_outputs,omitempty"`

	// LegacyTools are immutable script-tool names compiled from the selected
	// Workflow revision. They are resolved by the LazyMind Host when building
	// the isolated Workflow SubAgent tool set; the model never supplies them.
	LegacyTools []string `json:"legacy_tools,omitempty"`
}

// asMap serialises the params into the generic map expected by subagent.RunRequest.Params.
func (p WorkflowStepParams) asMap() map[string]any {
	m := map[string]any{
		"workflow_id":   p.WorkflowID,
		"step_id":       p.StepID,
		"session_id":    p.SessionID,
		"user_input":    p.UserInput,
		"is_cold_start": p.IsColdStart,
	}
	if p.WorkflowMode != "" {
		m["workflow_mode"] = p.WorkflowMode
	}
	if p.RevisionID != "" {
		m["revision_id"] = p.RevisionID
	}
	if p.TreeHash != "" {
		m["tree_hash"] = p.TreeHash
	}
	if p.HandOff != nil {
		m["hand_off"] = *p.HandOff
	}
	if p.PreflightID != "" {
		m["preflight_id"] = p.PreflightID
	}
	if p.ChatSessionID != "" {
		m["chat_session_id"] = p.ChatSessionID
	}
	if p.TraceID != "" && p.ParentSpanID != "" {
		m["trace_id"] = p.TraceID
		m["parent_span_id"] = p.ParentSpanID
	}
	if p.RetryHint != "" {
		m["retry_hint"] = p.RetryHint
	}
	if len(p.PartialIndices) > 0 {
		m["partial_indices"] = p.PartialIndices
	}
	if len(p.HistoryFilesPerTurn) > 0 {
		m["history_files_per_turn"] = p.HistoryFilesPerTurn
	}
	if len(p.ParentAgenticConfig) > 0 {
		m["parent_agentic_config"] = p.ParentAgenticConfig
	}
	if len(p.Filters) > 0 {
		m["filters"] = p.Filters
	}
	if p.UserID != "" {
		m["user_id"] = p.UserID
	}
	if len(p.LegacyTools) > 0 {
		m["legacy_tools"] = p.LegacyTools
	}
	return m
}

// WorkflowChatContext carries plugin identifiers threaded through the SubAgent event loop.
type WorkflowChatContext struct {
	SessionID           string
	WorkflowID          string
	StepID              string
	ConvID              string
	UserID              string
	WorkflowMode        string // "auto" | "dynamic"
	ChatSessionID       string
	TriggerHistoryID    string
	HistoryFilesPerTurn map[string][]string
	HandOff             *bool
}

type handoffBatchStep struct {
	StepID string
	Status string
}

func terminalWorkflowStepStatus(status string) bool {
	return status == subagent.StatusSucceeded || status == subagent.StatusFailed ||
		status == subagent.StatusInterrupted || status == subagent.StatusCanceled
}

func handoffStepName(stepID string, labels map[string]string) string {
	label := strings.TrimSpace(labels[stepID])
	if label == "" || label == stepID {
		return stepID
	}
	return fmt.Sprintf("%s（%s）", label, stepID)
}

func joinedHandoffStepNames(ids []string, labels map[string]string) string {
	sort.Strings(ids)
	names := make([]string, 0, len(ids))
	for _, id := range ids {
		names = append(names, handoffStepName(id, labels))
	}
	return strings.Join(names, "、")
}

// appendHandoffHistorySummary writes once after every SubTask launched by the same handoff
// turn is terminal. Parallel step statuses are merged into one concise history sentence.
func appendHandoffHistorySummary(
	ctx context.Context,
	db *gorm.DB,
	pctx *WorkflowChatContext,
	sessionCompleted bool,
) error {
	if db == nil || pctx == nil || strings.TrimSpace(pctx.TriggerHistoryID) == "" {
		return nil
	}
	handOff := true
	if pctx.HandOff != nil {
		handOff = *pctx.HandOff
	}
	if !handOff {
		return nil
	}
	labels := map[string]string{}
	var session orm.WorkflowSession
	if db.WithContext(ctx).Where("id = ?", pctx.SessionID).First(&session).Error == nil {
		if graph, err := loadSessionGraph(ctx, db, &session); err == nil {
			for id, node := range graph.Nodes {
				labels[id] = node.Label
			}
		}
	}

	return db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var batch []handoffBatchStep
		if err := tx.Table("plugin_session_steps AS steps"). // workflow-naming: persistence
									Select("steps.step_id, steps.status").
									Joins("JOIN sub_agent_tasks AS tasks ON tasks.id = steps.task_id").
									Where("steps.session_id = ? AND steps.validity <> ? AND tasks.trigger_history_id = ?",
				pctx.SessionID, "stale", pctx.TriggerHistoryID).
			Scan(&batch).Error; err != nil {
			return err
		}
		if len(batch) == 0 {
			return nil
		}
		for _, step := range batch {
			if !terminalWorkflowStepStatus(step.Status) {
				return nil
			}
		}

		var history orm.ChatHistory
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).
			Where("id = ? AND conversation_id = ?", pctx.TriggerHistoryID, pctx.ConvID).
			First(&history).Error; err != nil {
			return err
		}
		marker := fmt.Sprintf("<!-- workflow-handoff-summary:%s -->", pctx.TriggerHistoryID)
		if strings.Contains(history.Result, marker) {
			return nil
		}

		groups := map[string][]string{}
		for _, step := range batch {
			groups[step.Status] = append(groups[step.Status], step.StepID)
		}
		parts := make([]string, 0, 4)
		if ids := groups[subagent.StatusSucceeded]; len(ids) > 0 {
			parts = append(parts, "已完成 "+joinedHandoffStepNames(ids, labels))
		}
		interrupted := append(groups[subagent.StatusInterrupted], groups[subagent.StatusCanceled]...)
		if len(interrupted) > 0 {
			parts = append(parts, "用户中断了 "+joinedHandoffStepNames(interrupted, labels))
		}
		if ids := groups[subagent.StatusFailed]; len(ids) > 0 {
			parts = append(parts, "执行失败 "+joinedHandoffStepNames(ids, labels))
		}
		text := strings.Join(parts, "；") + "。"
		if sessionCompleted {
			text += " 工作流已完成。"
		}
		block := fmt.Sprintf("\n\n%s\n%s", marker, text)
		return tx.Model(&orm.ChatHistory{}).Where("id = ?", history.ID).Updates(map[string]any{
			"result":      strings.TrimSpace(history.Result) + block,
			"update_time": time.Now(),
		}).Error
	})
}

func conversationPreflight(ctx context.Context, db *gorm.DB, convID string) (map[string]any, map[string]any) {
	var conv orm.Conversation
	if db == nil || db.WithContext(ctx).Select("ext").Where("id = ?", convID).First(&conv).Error != nil {
		return nil, nil
	}
	ext := map[string]any{}
	if json.Unmarshal(conv.Ext, &ext) != nil {
		return nil, nil
	}
	preflight, _ := ext["workflow_preflight"].(map[string]any)
	return ext, preflight
}

func validateConversationPreflight(ctx context.Context, db *gorm.DB, convID, preflightID string) error {
	if strings.TrimSpace(preflightID) == "" {
		return nil // backward compatibility for callers that predate trigger preflight
	}
	_, preflight := conversationPreflight(ctx, db, convID)
	if preflight == nil || fmt.Sprint(preflight["preflight_id"]) != preflightID {
		return fmt.Errorf("plugin: prepared preflight is missing or stale")
	}
	if fmt.Sprint(preflight["status"]) != "ready" {
		return fmt.Errorf("plugin: preflight is not ready")
	}
	return nil
}

func consumeConversationPreflight(ctx context.Context, db *gorm.DB, convID, preflightID string) error {
	if strings.TrimSpace(preflightID) == "" {
		return nil
	}
	ext, preflight := conversationPreflight(ctx, db, convID)
	if preflight == nil || fmt.Sprint(preflight["preflight_id"]) != preflightID {
		return workflowRuntimeError("workflow: prepared preflight changed before it could be consumed")
	}
	delete(ext, "workflow_preflight")
	raw, _ := json.Marshal(ext)
	return db.WithContext(ctx).Model(&orm.Conversation{}).Where("id = ?", convID).Update("ext", raw).Error
}

type workflowRuntimeError string

func (e workflowRuntimeError) Error() string { return string(e) }

func enforceWorkflowConversationSettings(ctx context.Context, db *gorm.DB, convID string) error {
	if db == nil || strings.TrimSpace(convID) == "" {
		return nil
	}
	return db.WithContext(ctx).Model(&orm.Conversation{}).Where("id = ?", convID).Updates(map[string]any{
		"enable_plugin": true,      // workflow-naming: persistence
		"plugin_mode":   "dynamic", // workflow-naming: persistence
	}).Error
}

// HandleWorkflowStepCreated is the compatibility entry point for pre-v2
// task_created events. Graph-engine sessions use the synchronous transition API.
func HandleWorkflowStepCreated(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	convID, historyID, userID string,
	taskID, title, objective string,
	params WorkflowStepParams,
	inputKeys, outputKeys []string,
	llmConfig map[string]any,
	toolConfig map[string]any,
) (sessionID string, returnedTaskID string, workflowCompleted bool, err error) {
	if params.SessionID != "" {
		session, getErr := GetSession(ctx, db, params.SessionID)
		if getErr == nil && session.GraphSchemaVersion != "" {
			return "", taskID, false, fmt.Errorf("plugin: task_created is disabled for graph-engine session %s", params.SessionID)
		}
	}
	if params.StepID == "__end__" {
		if params.SessionID == "" {
			return "", taskID, false, fmt.Errorf("plugin: session_id required for legacy __end__ signal")
		}
		if _, createErr := CreateSessionStep(ctx, db, params.SessionID, "__end__", "__end__", 1); createErr != nil {
			return "", taskID, false, fmt.Errorf("plugin: persist legacy __end__: %w", createErr)
		}
		_ = UpdateStepStatus(ctx, db, "__end__", StepStatusSucceeded)
		if updateErr := UpdateSessionStatus(ctx, db, params.SessionID, SessionStatusCompleted); updateErr != nil {
			return "", taskID, false, fmt.Errorf("plugin: complete legacy session: %w", updateErr)
		}
		_ = taskcenter.UpdateTaskStatusBySession(ctx, db, params.SessionID, "succeeded")
		clearGeneratingChatStatus(ctx, stateStore, convID)
		return params.SessionID, taskID, true, nil
	}
	return launchWorkflowAttempt(
		ctx, db, stateStore, convID, historyID, userID, taskID, title, objective,
		params, inputKeys, outputKeys, llmConfig, toolConfig, true, true,
	)
}

// launchWorkflowAttempt persists and launches an attempt after its caller has
// performed admission. New transitions pass legacyEvent=false so the legacy
// single-current compatibility field is not mutated.
func launchWorkflowAttempt(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	convID, historyID, userID string,
	taskID, title, objective string,
	params WorkflowStepParams,
	inputKeys, outputKeys []string,
	llmConfig map[string]any,
	toolConfig map[string]any,
	legacyEvent bool,
	launchNow bool,
) (sessionID string, returnedTaskID string, workflowCompleted bool, err error) {
	workflowID := params.WorkflowID
	stepID := params.StepID
	isCold := params.IsColdStart
	returnedTaskID = taskID
	fmt.Printf("[plugin] attempt launch requested conv=%s session=%s plugin=%s step=%s task=%s cold=%t mode=%s legacy=%t\n",
		convID, params.SessionID, workflowID, stepID, taskID, isCold, params.WorkflowMode, legacyEvent)
	if params.ChatSessionID != "" {
		fmt.Printf("[plugin] task_created chat sid conv=%s chat_sid=%s plugin=%s step=%s task=%s\n",
			convID, params.ChatSessionID, workflowID, stepID, taskID)
	}

	if isCold {
		fmt.Printf("[plugin] cold-start branch conv=%s plugin=%s step=%s task=%s\n", convID, workflowID, stepID, taskID)
		psID := "ps_" + common.GenerateID()
		currentStepID := ""
		if legacyEvent {
			currentStepID = stepID
		}
		coldErr := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
			existing, gErr := GetActiveSession(ctx, tx, convID)
			if gErr != nil {
				return fmt.Errorf("plugin: check active session: %w", gErr)
			}
			if existing != nil {
				return fmt.Errorf("plugin: active session already exists (id=%s)", existing.ID)
			}
			if pErr := validateConversationPreflight(ctx, tx, convID, params.PreflightID); pErr != nil {
				return pErr
			}
			if _, sErr := CreateSession(ctx, tx, CreateSessionInput{
				SessionID:      psID,
				ConversationID: convID,
				WorkflowID:     workflowID,
				WorkflowRef:    params.WorkflowRef, WorkflowRevisionID: params.RevisionID, WorkflowRevisionNo: params.RevisionNo, WorkflowTreeHash: params.TreeHash, WorkflowRemoteRoot: params.RemoteRoot,
				TriggerHistoryID: historyID,
				CurrentStepID:    currentStepID,
				CreateUserID:     userID,
			}); sErr != nil {
				return fmt.Errorf("plugin: create session: %w", sErr)
			}
			if settingsErr := enforceWorkflowConversationSettings(ctx, tx, convID); settingsErr != nil {
				return fmt.Errorf("plugin: enforce conversation workflow settings: %w", settingsErr)
			}
			if strings.TrimSpace(params.UserInput) != "" {
				intentJSON, _ := json.Marshal(map[string]string{"text": params.UserInput})
				if err := tx.WithContext(ctx).Model(&orm.WorkflowSession{}).
					Where("id = ?", psID).
					Update("intent_context", string(intentJSON)).Error; err != nil {
					return fmt.Errorf("plugin: persist launch intent: %w", err)
				}
			}
			return consumeConversationPreflight(ctx, tx, convID, params.PreflightID)
		})
		if coldErr != nil {
			return "", "", false, coldErr
		}
		sessionID = psID
		fmt.Printf("[plugin] plugin session created conv=%s session=%s plugin=%s legacy_current_step=%s\n",
			convID, sessionID, workflowID, currentStepID)
		// Register a TaskCenter record for this plugin run so the user can track it.
		// Prefer conversation display_name as the task title so the task center shows
		// a human-readable conversation title instead of a raw plugin/step identifier.
		tcTitle := workflowID
		if title != "" {
			tcTitle = title
		}
		if db != nil {
			var conv orm.Conversation
			if err := db.WithContext(ctx).
				Select("display_name").
				Where("id = ?", convID).
				First(&conv).Error; err == nil && conv.DisplayName != "" {
				tcTitle = conv.DisplayName
			}
		}
		_ = taskcenter.CreateTask(ctx, db, &orm.TaskCenterTask{
			UserID:            userID,
			ConversationID:    convID,
			WorkflowSessionID: &sessionID,
			TaskType:          "workflow_run",
			Title:             &tcTitle,
			Status:            "running",
		})
		fmt.Printf("[plugin] taskcenter workflow_run ensured conv=%s session=%s plugin=%s\n",
			convID, sessionID, workflowID)
	} else {
		sessionID = params.SessionID
		fmt.Printf("[plugin] advance branch conv=%s session=%s plugin=%s step=%s task=%s\n",
			convID, sessionID, workflowID, stepID, taskID)
		if sessionID == "" {
			return "", "", false, fmt.Errorf("plugin: session_id required for non-cold-start step")
		}
		// Skip step advancement for dismissed sessions to prevent stale writes.
		existingSess, dsErr := GetSession(ctx, db, sessionID)
		if dsErr == nil && existingSess.Dismissed {
			return sessionID, taskID, false, fmt.Errorf("plugin: session %s is dismissed, skipping step advancement", sessionID)
		}
		if settingsErr := enforceWorkflowConversationSettings(ctx, db, convID); settingsErr != nil {
			return sessionID, taskID, false, fmt.Errorf("plugin: enforce conversation workflow settings: %w", settingsErr)
		}
		if legacyEvent {
			if uErr := UpdateSessionCurrentStep(ctx, db, sessionID, stepID); uErr != nil {
				return sessionID, taskID, false, fmt.Errorf("plugin: update legacy current step: %w", uErr)
			} else {
				fmt.Printf("[plugin] legacy session current_step updated conv=%s session=%s step=%s\n",
					convID, sessionID, stepID)
			}
		}
		// Ensure session is marked active when a new step starts (e.g. auto-advance via ChatAgent).
		if uErr := UpdateSessionStatus(ctx, db, sessionID, SessionStatusActive); uErr != nil {
			return sessionID, taskID, false, fmt.Errorf("plugin: activate session: %w", uErr)
		} else {
			fmt.Printf("[plugin] session status active conv=%s session=%s step=%s\n",
				convID, sessionID, stepID)
		}
		// A retry/rewind reopens a failed plugin run. Reset TaskCenter even when its
		// previous value was terminal so later success can be synchronized normally.
		_ = db.WithContext(ctx).Model(&orm.TaskCenterTask{}).
			Where("plugin_session_id = ?", sessionID). // workflow-naming: persistence
			Updates(map[string]any{"status": "running", "updated_at": time.Now().UTC()}).Error
	}

	// Inject artifacts from previous steps into objective, then append retry_hint if present.
	enrichedObjective := objective
	if params.RetryHint != "" {
		enrichedObjective += "\n\n--- Retry instruction (runtime only, not part of permanent prompt) ---\n" + params.RetryHint
	}

	// Create sub_agent_tasks record.
	// Python SubAgent reads params from the DB row (not the HTTP RunRequest body),
	// so attachment context and parent agentic_config must be persisted here.
	if len(params.HistoryFilesPerTurn) == 0 {
		params.HistoryFilesPerTurn = historyFilesFromConversation(db, convID)
	}
	if len(params.HistoryFilesPerTurn) == 0 {
		params.HistoryFilesPerTurn = historyFilesFromParentAgentic(params.ParentAgenticConfig)
	}
	rawParamsMap := map[string]any{
		"workflow_id":   workflowID,
		"step_id":       stepID,
		"session_id":    sessionID,
		"user_input":    params.UserInput,
		"is_cold_start": isCold,
	}
	refOrID := params.WorkflowRef
	if refOrID == "" {
		refOrID = workflowID
	}
	if outputTypes := declaredWorkflowOutputTypes(ctx, db, userID, refOrID, params.RevisionID, outputKeys); len(outputTypes) > 0 {
		rawParamsMap["output_slot_types"] = outputTypes
	}
	if params.RevisionID != "" {
		rawParamsMap["revision_id"] = params.RevisionID
	}
	if params.TreeHash != "" {
		rawParamsMap["tree_hash"] = params.TreeHash
	}
	if !legacyEvent {
		// Compiled graph outputs are material guarantees. A v2 attempt cannot
		// succeed unless every declared output was actually persisted.
		rawParamsMap["required_output_artifact_keys"] = params.RequiredOutputs
	}
	if len(params.LegacyTools) > 0 {
		rawParamsMap["legacy_tools"] = params.LegacyTools
	}
	if params.HandOff != nil {
		rawParamsMap["hand_off"] = *params.HandOff
	}
	if params.PreflightID != "" {
		rawParamsMap["preflight_id"] = params.PreflightID
	}
	if params.WorkflowMode != "" {
		rawParamsMap["workflow_mode"] = params.WorkflowMode
	}
	if params.ChatSessionID != "" {
		rawParamsMap["chat_session_id"] = params.ChatSessionID
	}
	if params.TraceID != "" && params.ParentSpanID != "" {
		rawParamsMap["trace_id"] = params.TraceID
		rawParamsMap["parent_span_id"] = params.ParentSpanID
	}
	if params.RetryHint != "" {
		rawParamsMap["retry_hint"] = params.RetryHint
	}
	if len(params.PartialIndices) > 0 {
		rawParamsMap["partial_indices"] = params.PartialIndices
	}
	if len(params.HistoryFilesPerTurn) > 0 {
		rawParamsMap["history_files_per_turn"] = params.HistoryFilesPerTurn
	}
	if len(params.ParentAgenticConfig) > 0 {
		rawParamsMap["parent_agentic_config"] = params.ParentAgenticConfig
	}
	filters := params.Filters
	if len(filters) == 0 {
		filters = filtersFromConversation(db, convID)
		if len(filters) > 0 {
			params.Filters = filters
		}
	}
	if len(filters) == 0 && len(params.ParentAgenticConfig) > 0 {
		if parentFilters, ok := params.ParentAgenticConfig["filters"].(map[string]any); ok && len(parentFilters) > 0 {
			filters = parentFilters
			params.Filters = parentFilters
		}
	}
	if len(filters) > 0 {
		rawParamsMap["filters"] = filters
	}
	if params.UserID != "" {
		rawParamsMap["user_id"] = params.UserID
	}
	rawParams, _ := json.Marshal(rawParamsMap)
	inputJSON, _ := json.Marshal(inputKeys)
	outputJSON, _ := json.Marshal(outputKeys)
	task, cErr := subagent.CreateTask(ctx, db, subagent.CreateTaskInput{
		TaskID:           taskID,
		ConversationID:   convID,
		TriggerHistoryID: historyID,
		AgentType:        "workflow_step",
		Title:            workflowID + ":" + stepID,
		Objective:        enrichedObjective,
		Mode:             "manual",
		Params:           rawParams,
		InputSlots:       inputJSON,
		OutputSlots:      outputJSON,
		WorkspacePath:    subagent.WorkspacePath(userID, taskID),
		CreateUserID:     userID,
	})
	if cErr != nil {
		return "", sessionID, false, fmt.Errorf("plugin: create sub_agent_task: %w", cErr)
	}
	fmt.Printf("[plugin] sub_agent_task created conv=%s session=%s plugin=%s step=%s task=%s workspace=%s\n",
		convID, sessionID, workflowID, stepID, task.ID, task.WorkspacePath)

	// Create plugin_session_steps record.  // workflow-naming: persistence
	attempt, attemptErr := NextAttempt(ctx, db, sessionID, stepID)
	if attemptErr != nil {
		return sessionID, task.ID, false, fmt.Errorf("plugin: allocate attempt: %w", attemptErr)
	}
	if _, stepErr := CreateSessionStep(ctx, db, sessionID, stepID, task.ID, attempt); stepErr != nil {
		return sessionID, task.ID, false, fmt.Errorf("plugin: create session step: %w", stepErr)
	} else {
		fmt.Printf("[plugin] workflow_session_step created conv=%s session=%s step=%s task=%s attempt=%d\n",
			convID, sessionID, stepID, task.ID, attempt)
	}
	runParams := map[string]any{
		"workflow_id": workflowID,
		"step_id":     stepID,
		"session_id":  sessionID,
	}
	if params.TraceID != "" && params.ParentSpanID != "" {
		runParams["trace_id"] = params.TraceID
		runParams["parent_span_id"] = params.ParentSpanID
	}
	if len(params.HistoryFilesPerTurn) > 0 {
		runParams["history_files_per_turn"] = params.HistoryFilesPerTurn
	}
	if len(params.ParentAgenticConfig) > 0 {
		runParams["parent_agentic_config"] = params.ParentAgenticConfig
	}
	runRequest := subagent.RunRequest{
		TaskID: task.ID, AgentType: "workflow_step", WorkspacePath: task.WorkspacePath,
		Params: runParams, DBDSN: subagent.DBDSN(), Resume: false,
		LLMConfig: llmConfig, ToolConfig: toolConfig,
	}
	if enqueueErr := enqueueWorkflowAttemptRunner(ctx, db, runRequest); enqueueErr != nil {
		return sessionID, task.ID, false, fmt.Errorf("plugin: enqueue attempt runner: %w", enqueueErr)
	}

	return sessionID, task.ID, false, nil
}

func enqueueWorkflowAttemptRunner(ctx context.Context, db *gorm.DB, request subagent.RunRequest) error {
	return enqueueCanonicalAttempt(ctx, db, request)
}

// OnSubAgentDone is called when a workflow_step task reaches terminal status.
// It mirrors the step status and handles auto/dynamic advance logic.
//
// Successful v2 attempts freeze their route decision and let the graph
// projector determine completion. Legacy sessions retain their waiting flow.
func OnSubAgentDone(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	taskID, status, summary string,
	onSSE func(eventType string, payload map[string]any),
	pctx *WorkflowChatContext,
) {
	_ = UpdateStepStatus(ctx, db, taskID, status)
	stepFailed := status != subagent.StatusSucceeded && status != subagent.StatusInterrupted
	sessionCompleted := false
	if status == subagent.StatusSucceeded && pctx != nil && pctx.SessionID != "" {
		if err := freezeRouteDecision(ctx, db, pctx.SessionID, pctx.StepID, taskID); err != nil {
			fmt.Printf("[plugin] freeze route decision failed session=%s step=%s err=%v\n", pctx.SessionID, pctx.StepID, err)
		} else {
			var session orm.WorkflowSession
			if db.WithContext(ctx).Select("status").Where("id = ?", pctx.SessionID).First(&session).Error == nil {
				sessionCompleted = session.Status == SessionStatusCompleted
			}
		}
	}
	if err := appendHandoffHistorySummary(ctx, db, pctx, sessionCompleted); err != nil {
		fmt.Printf("[plugin] persist handoff history summary failed task=%s err=%v\n", taskID, err)
	}

	if stepFailed {
		// Non-succeeded, non-interrupted (i.e. truly failed) steps: notify the frontend
		// and mark the session failed. Auto mode still asks DriverAgent to diagnose
		// and recommend retry/rewind; dynamic mode leaves the failure for the user.
		if pctx != nil && pctx.SessionID != "" {
			_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusFailed)
			_ = taskcenter.UpdateTaskStatusBySession(ctx, db, pctx.SessionID, "failed")
			clearGeneratingChatStatus(ctx, stateStore, pctx.ConvID)
			go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
		}
		// Publish only after authoritative state is durable; consumers may reload
		// the Session immediately when they receive this terminal event.
		if pctx != nil {
			onSSE("workflow_error", map[string]any{
				"session_id": pctx.SessionID,
				"step_id":    pctx.StepID,
				"message":    summary,
			})
		}
	}

	if pctx == nil {
		return
	}

	// Check whether sibling steps in the same session are still running.
	// If any step is still running, emit step_parallel_done for UI progress and wait.
	// Only the last step to complete triggers the advance logic.
	// Note: UpdateStepStatus above has already set this step to a terminal status,
	// so the running count will not include the current step.
	if pctx.SessionID != "" {
		var runningCount int64
		db.WithContext(ctx).Model(&orm.WorkflowSessionStep{}).
			Where("session_id = ? AND status = ?", pctx.SessionID, StepStatusRunning).
			Count(&runningCount)
		if runningCount > 0 {
			onSSE("step_partial_done", map[string]any{
				"session_id": pctx.SessionID,
				"step_id":    pctx.StepID,
			})
			return
		}
	}

	if sessionCompleted {
		_ = taskcenter.UpdateTaskStatusBySession(ctx, db, pctx.SessionID, "succeeded")
		clearGeneratingChatStatus(ctx, stateStore, pctx.ConvID)
		onSSE("workflow_completed", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
		})
		go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
		return
	}

	// Determine mode: use context-level WorkflowMode (set from request body during HandleWorkflowStepCreated).
	// Falls back to "dynamic" if not set. Env-var defaultMode() is no longer used.
	mode := pctx.WorkflowMode
	if mode != "auto" && mode != "dynamic" {
		mode = "dynamic"
	}
	fmt.Printf("[plugin] sub_agent terminal conv=%s session=%s step=%s task=%s status=%s mode=%s summary_len=%d\n",
		pctx.ConvID, pctx.SessionID, pctx.StepID, taskID, status, mode, len(summary))
	if stepFailed {
		if mode == "auto" {
			go advanceAutoMode(context.Background(), db, stateStore, status, summary, onSSE, pctx)
		}
		return
	}

	handOff := true // legacy tasks only had the hand-off advancement tool by default
	if pctx.HandOff != nil {
		handOff = *pctx.HandOff
	}
	if !handOff {
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
		onSSE("step_waiting", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"reason":     "inline_complete",
		})
		go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
		return
	}

	if mode == "auto" {
		// Interrupted steps should not be auto-advanced: surface the interruption to the user
		// so they can explicitly choose to continue (checkpoint resume) or retry.
		if status == subagent.StatusInterrupted {
			_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
			onSSE("step_waiting", map[string]any{
				"session_id": pctx.SessionID,
				"step_id":    pctx.StepID,
				"reason":     "interrupted",
			})
			return
		}
		// Use a detached context: ctx originates from the SubAgent Run loop and is
		// cancelled as soon as Run returns, before this goroutine loads LLM config.
		go advanceAutoMode(context.Background(), db, stateStore, status, summary, onSSE, pctx)
	} else {
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
		onSSE("step_waiting", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"reason":     "dynamic_pause",
		})
	}
	// Write content_snapshot to all selected revisions for this step.
	go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
}

func clearGeneratingChatStatus(ctx context.Context, stateStore state.Store, convID string) {
	if stateStore == nil || strings.TrimSpace(convID) == "" {
		return
	}
	key := fmt.Sprintf("rag/chat/status:%s", convID)
	entries, err := stateStore.HGetAll(ctx, key)
	if err != nil {
		return
	}
	var fields []string
	for historyID, raw := range entries {
		var st chatStatusCacheEntry
		if json.Unmarshal([]byte(raw), &st) != nil {
			continue
		}
		if st.Status == "generating" {
			fields = append(fields, historyID)
		}
	}
	if len(fields) > 0 {
		_ = stateStore.HDel(ctx, key, fields...)
	}
}

// advanceAutoMode calls DriverAgent and forwards its natural-language assessment to ChatAgent.
// ChatAgent then decides autonomously whether to advance, retry, or rewind.
// Go's graph projector determines session completion.
func advanceAutoMode(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	terminalStatus string,
	summary string,
	onSSE func(string, map[string]any),
	pctx *WorkflowChatContext,
) {
	step, _ := GetLatestStep(ctx, db, pctx.SessionID, pctx.StepID)
	attempt := 0
	if step != nil {
		attempt = step.Attempt
	}

	llmConfig, configErr := modelconfig.LoadLLMConfig(ctx, db, pctx.UserID)
	if configErr != nil {
		fmt.Printf("[Workflow] load DriverAgent LLM config failed user=%s err=%v\n", pctx.UserID, configErr)
	}
	acceptance, driverPrompt := loadWorkflowDriverPolicy(ctx, db, pctx.SessionID, pctx.StepID)
	artifactsSummary, _ := buildWorkflowArtifactsSummary(ctx, db, pctx.SessionID, pctx.StepID)
	driverInput := fmt.Sprintf("Terminal status: %s\nAttempt: %d\n%s", terminalStatus, attempt, summary)
	driverMsg, fallback := callWorkflowDriverAgent(
		pctx.WorkflowID, pctx.StepID, driverInput, acceptance, driverPrompt, pctx.SessionID,
		pctx.HistoryFilesPerTurn, llmConfig, artifactsSummary,
	)
	if fallback {
		onSSE("driver_fallback", map[string]any{
			"session_id": pctx.SessionID, "step_id": pctx.StepID,
			"reason": "driver_unavailable",
		})
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
		onSSE("step_waiting", map[string]any{
			"session_id": pctx.SessionID, "step_id": pctx.StepID,
			"reason": "driver_fallback",
		})
		return
	}
	onSSE("driver_input", map[string]any{
		"session_id": pctx.SessionID,
		"step_id":    pctx.StepID,
		"message":    driverMsg,
	})
	pctxCopy := *pctx
	go func() {
		triggerNextChatTurn(pctxCopy.ConvID, pctxCopy.SessionID, pctxCopy.WorkflowID, pctxCopy.StepID,
			pctxCopy.WorkflowMode, pctxCopy.UserID, driverMsg, func() {
				// Emit after core has accepted the request and set Redis generating status,
				// so the frontend resume SSE does not race with stream setup.
				onSSE("auto_chat_started", map[string]any{
					"session_id":      pctxCopy.SessionID,
					"conversation_id": pctxCopy.ConvID,
					"driver_message":  driverMsg,
				})
			}, "driver")
		checkAndFallbackIfStuck(ctx, db, stateStore, onSSE, &pctxCopy)
	}()
}

// triggerNextChatTurn sends a synthetic POST /conversations:chat to Go core to trigger
// the next ChatAgent round. This ensures history persistence, applyChatRuntimeConfigs,
// and all other Go-side pipeline steps run exactly as in a real user turn.
func triggerNextChatTurn(
	convID, sessionID, workflowID, currentStep, workflowMode, userID, syntheticMsg string,
	onReady func(),
	syntheticSource string,
) {
	coreURL := common.CoreSelfEndpoint() + "/conversations:chat"
	workflowCtx := map[string]any{
		"session_id":    sessionID,
		"workflow_id":   workflowID,
		"current_step":  currentStep,
		"workflow_mode": workflowMode,
	}
	if syntheticSource != "" {
		workflowCtx["synthetic_source"] = syntheticSource
	}
	reqBody := map[string]any{
		"query":           syntheticMsg,
		"conversation_id": convID,
		// stream=true is required so that task_created events emitted by the ChatAgent
		// are written to the Redis SSE buffer and delivered to the frontend.
		// Non-streaming mode skips the event pipeline entirely.
		"stream":           true,
		"mode":             "auto",
		"input":            []map[string]any{{"input_type": "text", "text": syntheticMsg}},
		"workflow_context": workflowCtx,
	}
	if searchConfig := loadConversationSearchConfig(store.DB(), convID); len(searchConfig) > 0 {
		reqBody["conversation"] = map[string]any{"search_config": searchConfig}
	}
	body, _ := json.Marshal(reqBody)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, coreURL, bytes.NewReader(body))
	if err != nil {
		fmt.Printf("[Workflow] triggerNextChatTurn: build request: %v\n", err)
		return
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "text/event-stream")
	req.Header.Set("X-User-Id", userID)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Printf("[Workflow] triggerNextChatTurn: send request: %v\n", err)
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		fmt.Printf("[Workflow] triggerNextChatTurn: core returned %d\n", resp.StatusCode)
		return
	}
	if onReady != nil {
		onReady()
	}
	// Drain the SSE response body. We do not relay the stream anywhere; Go core
	// writes all events (including task_created) directly to Redis. Draining is
	// required to keep the connection alive until the upstream finishes.
	buf := make([]byte, 4096)
	for {
		if _, err := resp.Body.Read(buf); err != nil {
			break
		}
	}
}

// checkAndFallbackIfStuck is called after triggerNextChatTurn returns (stream drained).
// If ChatAgent did not call advance_step the session remains active even though no
// SubAgent is running. This function detects that condition and demotes the session to
// waiting so the frontend can prompt the user for input.
func checkAndFallbackIfStuck(
	ctx context.Context,
	db *gorm.DB,
	_ state.Store,
	onSSE func(string, map[string]any),
	pctx *WorkflowChatContext,
) {
	// Brief pause to let any in-flight HandleWorkflowStepCreated DB writes settle.
	time.Sleep(500 * time.Millisecond)
	session, err := GetSession(ctx, db, pctx.SessionID)
	if err != nil || session == nil {
		return
	}
	if session.Status != SessionStatusActive {
		// Session was already advanced or completed — nothing to do.
		return
	}
	// A workflow_step SubAgent may still be running (advance_step succeeded); keep session active.
	var runningCount int64
	if err := db.WithContext(ctx).Model(&orm.WorkflowSessionStep{}).
		Where("session_id = ? AND status = ?", pctx.SessionID, StepStatusRunning).
		Count(&runningCount).Error; err == nil && runningCount > 0 {
		return
	}
	// Session is still active but no SubAgent is running: ChatAgent did not push a new step.
	_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
	onSSE("step_waiting", map[string]any{
		"session_id": pctx.SessionID,
		"step_id":    pctx.StepID,
		"reason":     "chat_agent_no_advance",
	})
}

// OnArtifactEvent is called when a workflow_step SubAgent emits an artifact event.
// It checks slot binding and writes plugin_slot_revisions if the artifact is bound.  // workflow-naming: persistence
// Caption embedded in the artifact value is written to sub_agent_artifacts.caption.
//
// For list-cardinality slots, the artifact value may carry a "list_index" field
// (written by save_artifacts) that enables partial retry: only the revision at that
// index is replaced; other indices remain untouched.
// When "list_index" is absent the item is appended at the next available index.
func OnArtifactEvent(
	ctx context.Context,
	db *gorm.DB,
	taskID, slot string,
	pctx *WorkflowChatContext,
) *orm.WorkflowSlotRevision {
	if pctx == nil {
		return nil
	}
	slotID, cardinality := resolveSlotBinding(pctx.WorkflowID, slot)
	if slotID == "" {
		return nil
	}
	attempt := 1
	step, _ := GetLatestStep(ctx, db, pctx.SessionID, pctx.StepID)
	if step != nil {
		attempt = step.Attempt
	}

	// For list slots, extract list_index from the artifact value if present.
	var listIndex *int
	if cardinality == "list" {
		listIndex = extractListIndex(ctx, db, taskID, slot)
	}

	// Extract caption from artifact value and write it to sub_agent_artifacts.caption.
	// PostgreSQL does not support UPDATE with ORDER BY/LIMIT, so we first fetch the
	// target row's primary key (task_id + slot + seq), then update by PK.
	if caption := extractCaption(ctx, db, taskID, slot); caption != "" {
		var target orm.SubAgentArtifact
		if db.WithContext(ctx).
			Where("task_id = ? AND slot = ?", taskID, slot).
			Order("seq DESC").
			First(&target).Error == nil {
			_ = db.WithContext(ctx).Model(&orm.SubAgentArtifact{}).
				Where("task_id = ? AND slot = ? AND seq = ?", target.TaskID, target.Slot, target.Seq).
				Update("caption", caption).Error
		}
	}

	rev, err := WriteSlotRevision(ctx, db,
		pctx.SessionID, slotID, slot, pctx.StepID, attempt, cardinality, listIndex)
	if err != nil {
		fmt.Printf("[Workflow] WriteSlotRevision failed: %v\n", err)
		return nil
	}

	// Back-fill list_index into sub_agent_artifacts.value so that HideSlotItem
	// can match the artifact row by list_index when the user deletes an item.
	// This is needed for append-mode artifacts where Python does not yet know
	// the list_index assigned by Go (sort_order was not passed to save_artifacts).
	if cardinality == "list" && rev != nil && rev.ListIndex != nil {
		backfillArtifactListIndex(ctx, db, taskID, slot, *rev.ListIndex)
	}
	return rev
}

// OnSubAgentDoneSnapshot back-fills artifact_seq on any AI slot revision that was
// written before the artifact row existed (i.e. artifact_seq is still NULL).
// This covers the race where WriteSlotRevision ran before save_artifacts committed.
// Human revisions (change_source='human') are never touched.
func OnSubAgentDoneSnapshot(
	ctx context.Context,
	db *gorm.DB,
	pctx *WorkflowChatContext,
) {
	if pctx == nil {
		return
	}
	revisions, err := LoadSelectedSlots(ctx, db, pctx.SessionID)
	if err != nil {
		fmt.Printf("[Workflow] OnSubAgentDoneSnapshot: load slots: %v\n", err)
		return
	}

	step, _ := GetLatestStep(ctx, db, pctx.SessionID, pctx.StepID)
	if step == nil {
		return
	}

	for _, rev := range revisions {
		if rev.StepID != pctx.StepID || rev.Attempt != step.Attempt {
			continue
		}
		// Only fix AI revisions where artifact_seq was not resolved at write time.
		if rev.ChangeSource != "ai" || rev.ArtifactSeq != nil {
			continue
		}

		// Find the matching artifact row.
		var art orm.SubAgentArtifact
		if rev.ListIndex != nil {
			var candidates []orm.SubAgentArtifact
			db.WithContext(ctx).
				Where("task_id = ? AND slot = ?", step.TaskID, rev.Slot).
				Order("seq DESC").
				Find(&candidates)
			for _, c := range candidates {
				var v map[string]any
				if json.Unmarshal(c.Value, &v) != nil {
					continue
				}
				var liInt int
				switch idx := v["list_index"].(type) {
				case float64:
					liInt = int(idx)
				case int:
					liInt = idx
				default:
					continue
				}
				if liInt == *rev.ListIndex {
					art = c
					break
				}
			}
			if art.TaskID == "" {
				continue
			}
		} else {
			if err := db.WithContext(ctx).
				Where("task_id = ? AND slot = ?", step.TaskID, rev.Slot).
				Order("seq DESC").
				First(&art).Error; err != nil {
				continue
			}
		}

		seq := art.Seq
		if err := db.WithContext(ctx).Model(&orm.WorkflowSlotRevision{}).
			Where("id = ?", rev.ID).
			Update("artifact_seq", seq).Error; err != nil {
			fmt.Printf("[Workflow] OnSubAgentDoneSnapshot: backfill artifact_seq rev=%s: %v\n", rev.ID, err)
		}
	}
}

// extractListIndex reads the most recent artifact value for the given (taskID, slot)
// and returns the list_index embedded in the JSON value, or nil if absent.
func extractListIndex(ctx context.Context, db *gorm.DB, taskID, slot string) *int {
	var a orm.SubAgentArtifact
	err := db.WithContext(ctx).
		Where("task_id = ? AND slot = ?", taskID, slot).
		Order("seq DESC").
		First(&a).Error
	if err != nil {
		return nil
	}
	var v map[string]any
	if json.Unmarshal(a.Value, &v) != nil {
		return nil
	}
	raw, ok := v["list_index"]
	if !ok {
		return nil
	}
	switch idx := raw.(type) {
	case float64:
		i := int(idx)
		return &i
	case int:
		return &idx
	}
	return nil
}

// extractCaption reads the most recent artifact value for the given (taskID, slot)
// and returns the caption string embedded in the JSON value, or "" if absent.
func extractCaption(ctx context.Context, db *gorm.DB, taskID, slot string) string {
	var a orm.SubAgentArtifact
	err := db.WithContext(ctx).
		Where("task_id = ? AND slot = ?", taskID, slot).
		Order("seq DESC").
		First(&a).Error
	if err != nil {
		return ""
	}
	var v map[string]any
	if json.Unmarshal(a.Value, &v) != nil {
		return ""
	}
	if cap, ok := v["caption"].(string); ok {
		return strings.TrimSpace(cap)
	}
	return ""
}

// resolveSlotBinding is retained only for the pre-public callback below. Public
// Host outputs are resolved and persisted by executor.ArtifactSink.
func resolveSlotBinding(workflowID, slot string) (slotID, cardinality string) {
	return "", ""
}

func callWorkflowDriverAgent(
	workflowID, stepID, stepResult, acceptance, driverPrompt, sessionID string,
	historyFilesPerTurn map[string][]string,
	llmConfig map[string]any,
	artifactsSummary string,
) (string, bool) {
	doCall := func() (string, bool) {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()
		body, _ := json.Marshal(map[string]any{
			"workflow_id": workflowID, "step_id": stepID, "step_result": stepResult,
			"acceptance": acceptance, "driver_prompt": driverPrompt, "session_id": sessionID,
			"history_files_per_turn": historyFilesPerTurn, "llm_config": llmConfig,
			"workflow_artifacts_summary": artifactsSummary,
		})
		req, err := http.NewRequestWithContext(ctx, http.MethodPost,
			common.ChatServiceEndpoint()+"/api/workflow/driver", bytes.NewReader(body))
		if err != nil {
			return "", true
		}
		req.Header.Set("Content-Type", "application/json")
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return "", true
		}
		defer resp.Body.Close()
		var value struct {
			Message string `json:"message"`
		}
		if resp.StatusCode != http.StatusOK || json.NewDecoder(resp.Body).Decode(&value) != nil || strings.TrimSpace(value.Message) == "" {
			return "", true
		}
		return value.Message, false
	}
	message, fallback := doCall()
	if fallback {
		time.Sleep(5 * time.Second)
		message, fallback = doCall()
	}
	return message, fallback
}

func loadWorkflowDriverPolicy(ctx context.Context, db *gorm.DB, sessionID, stepID string) (string, string) {
	session, err := GetSession(ctx, db, sessionID)
	if err != nil || session == nil {
		return "", ""
	}
	acceptance := ""
	if graph, graphErr := loadSessionGraph(ctx, db, session); graphErr == nil {
		if node, ok := graph.Nodes[stepID]; ok {
			acceptance = strings.Join(node.Acceptance, "\n")
		}
	}
	if session.WorkflowRevisionID == "" {
		return acceptance, ""
	}
	var blob orm.WorkflowBlob
	err = db.WithContext(ctx).Table("plugin_blobs AS b").
		Select("b.*").
		Joins("JOIN plugin_revision_entries AS e ON e.blob_hash = b.hash").
		Where("e.revision_id = ? AND e.path = ?", session.WorkflowRevisionID, "scenario/driver.md").
		First(&blob).Error
	if err != nil {
		return acceptance, ""
	}
	return acceptance, string(blob.Content)
}

// buildWorkflowArtifactsSummary builds a text summary of all artifacts produced in this
// plugin session and the current step, for injection into the DriverAgent evaluation context.
func buildWorkflowArtifactsSummary(ctx context.Context, db *gorm.DB, sessionID, stepID string) (string, error) {
	if db == nil || sessionID == "" {
		return "", nil
	}
	// Gather all sub_agent_artifacts for completed steps in this session.
	type artifactRow struct {
		Slot   string `gorm:"column:slot"`
		Value  []byte `gorm:"column:value"`
		TaskID string `gorm:"column:task_id"`
	}
	var rows []artifactRow
	err := db.WithContext(ctx).Raw(`
		SELECT sa.slot, sa.value, sa.task_id
		FROM sub_agent_artifacts sa
		JOIN plugin_session_steps pss ON pss.task_id = sa.task_id
		WHERE pss.session_id = ? AND pss.status = 'succeeded'
		ORDER BY sa.task_id, sa.slot, sa.seq
	`, sessionID).Scan(&rows).Error
	if err != nil || len(rows) == 0 {
		return "", err
	}
	var sb strings.Builder
	sb.WriteString("## Workflow session artifacts\n")
	for _, r := range rows {
		var v map[string]any
		if json.Unmarshal(r.Value, &v) == nil {
			if val, ok := v["value"]; ok {
				sb.WriteString(fmt.Sprintf("- %s: %v\n", r.Slot, val))
				continue
			}
		}
		sb.WriteString(fmt.Sprintf("- %s: %s\n", r.Slot, string(r.Value)))
	}
	return sb.String(), nil
}

// backfillArtifactListIndex patches the most-recent sub_agent_artifacts row for
// (taskID, slot) to embed {"list_index": listIndex} inside its value JSON.
// This ensures HideSlotItem can match artifacts by list_index even when the AI
// wrote the artifact in append-mode (no sort_order → no list_index in value at write time).
// Skipped silently if the row already contains the correct list_index.
func backfillArtifactListIndex(ctx context.Context, db *gorm.DB, taskID, slot string, listIndex int) {
	var art orm.SubAgentArtifact
	if err := db.WithContext(ctx).
		Where("task_id = ? AND slot = ?", taskID, slot).
		Order("seq DESC").
		First(&art).Error; err != nil {
		return
	}
	var v map[string]any
	if json.Unmarshal(art.Value, &v) != nil {
		return
	}
	// Already correct — no update needed.
	if existing, ok := v["list_index"]; ok {
		switch idx := existing.(type) {
		case float64:
			if int(idx) == listIndex {
				return
			}
		case int:
			if idx == listIndex {
				return
			}
		}
	}
	v["list_index"] = listIndex
	newVal, err := json.Marshal(v)
	if err != nil {
		return
	}
	_ = db.WithContext(ctx).Model(&orm.SubAgentArtifact{}).
		Where("task_id = ? AND slot = ? AND seq = ?", art.TaskID, art.Slot, art.Seq).
		Update("value", newVal).Error
}
